googleapis/google-api-dotnet-client

Src/GoogleApis.Auth/OAuth2/Flows/AuthorizationCodeFlow.cs
Src/GoogleApis.Auth/OAuth2/Requests/TokenRequestExtenstions.cs
Src/GoogleApis.Auth/Properties/AssemblyInfo.cs
Src/GoogleApis.Core/Apis/Http/ConfigurableMessageHandler.cs
Src/GoogleApis.Core/Apis/Http/HttpExtenstions.cs
Src/GoogleApis.Core/Apis/Http/MaxUrlLengthInterceptor.cs
Src/GoogleApis.Core/Apis/Requests/Parameters/ParameterValidator.cs
Src/GoogleApis.Core/Apis/Testing/VisibleForTestOnly.cs
Src/GoogleApis.Core/Apis/Util/Utilities.cs
Src/GoogleApis.Core/ApplicationContext.cs
Src/GoogleApis.Core/Properties/AssemblyInfo.cs
Src/GoogleApis.Tests/Apis/Services/BaseClientServiceTest.cs
Src/GoogleApis.Tests/Apis/Upload/ResumableUploadTest.cs
Src/GoogleApis.Tests/Apis/Utils/UtilitiesTest.cs
Src/GoogleApis.Tests/ApplicationContextTests.cs
Src/GoogleApis/Apis/Requests/BatchRequest.cs
Src/GoogleApis/Apis/Requests/ClientServiceRequest.cs
Src/GoogleApis/Apis/Services/BaseClientService.cs
Src/GoogleApis/Apis/[Media]/Upload/ResumableUpload.cs
Src/GoogleApis/Properties/AssemblyInfo.cs

http://codereview.appspot.com/230740044/
This change is in order to eventually sign the dlls.
It seams that "friend assemblies" will make the process of signing our Google.Apis dlls just harder, and it is easy to remove the IntternalsVisibleTo attributes.

Remove InternalsVisibleTo (Friend assembly) from the codebase

---

Src/GoogleApis.Auth.DotNet4/OAuth2/ServiceAccountCredential.cs

Adjust JWT signing to be FIPS compliant. 
According to the following article, RsaCryptoServiceProvider's hash mechanism is not FIPS compliant, and exceptions will be thrown on FIPS enabled systems.  This PR performs the hashing and signing in two separate steps -- with the hashing occurring via SHA256CryptoServiceProvider, which makes FIPS happy.
https://connect.microsoft.com/VisualStudio/feedback/details/584754/using-sha256-with-rsacryptoserviceprovider-in-a-webapplication

Switch ServiceAccountCredential signing to be FIPS compliant

---

Src/GoogleApis.Auth.DotNet4/GoogleApis.Auth.DotNet4.csproj
Src/GoogleApis.Auth.DotNet4/OAuth2/ServiceAccountCredential.cs
Src/GoogleApis.Auth.DotNet4/packages.config
Tools/Google.Apis.Release/Resources/Google.Apis.Auth.VERSION.nuspec

Adds support for JSON Service Account keys, generated from cloud console using the "Generate New JSON Key" option as described here https://developers.google.com/identity/protocols/OAuth2ServiceAccount.
This contains code of #552 (already LGTMd), rebased on top of upstream/master and with the commits squashed together to preserve clean git history.
FYI @vsubramani, who is the author of the code (as the commit author info suggests)

add JSON Service Account credential support

---

Src/GoogleApis.Auth.DotNet4/OAuth2/ServiceAccountCredential.cs
Src/GoogleApis.Auth/OAuth2/ServiceCredential.cs

Adding ConfigureAwait(false) where missing

---

Src/GoogleApis.Core/GoogleApiException.cs
Src/GoogleApis/Apis/Requests/ClientServiceRequest.cs
Src/GoogleApis/Apis/Services/BaseClientService.cs
Src/GoogleApis/Apis/[Media]/Upload/ResumableUpload.cs

Expose RequestError in GoogleApiException when available

---

Src/GoogleApis.Auth.WP/OAuth2/WebAuthenticationBrokerUserControl.xaml.cs

It seems there is a rather serious problem with the GoogleWebAuthorizationBroker.AuthorizeAsync invocation. Somewhere deep inside the code flow there is WebAuthenticationBrokerUserControl class and the method OnBrowserNavigating. This method constantly throwing this exception
System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
at Google.Apis.Auth.OAuth2.WebAuthenticationBrokerUserControl.OnBrowserNavigating(Object sender, NavigatingEventArgs e)
at Microsoft.Phone.Controls.WebBrowser.FireNavigatingEvent(Uri uri, Boolean& cancel) at Microsoft.Phone.Controls.WebBrowserInterop.ReversePInvokeThunk.OnNavigating(Int32 webBrowserControlId, String uri, …

Fixing exception InvalidOperationException while authentication

---

Src/GoogleApis.Auth/OAuth2/ServiceCredential.cs
Src/GoogleApis.Auth/OAuth2/UserCredential.cs
Src/GoogleApis.Core/Apis/Http/ConfigurableMessageHandler.cs
Src/GoogleApis.Core/Apis/Http/ExponentialBackOffInitializer.cs
Src/GoogleApis.Tests/Apis/Http/ConfigurableMessageHandlerTest.cs
Src/GoogleApis.Tests/Apis/Http/MaxUrlLengthInterceptorTest.cs
Src/GoogleApis.Tests/Apis/Requests/ClientServiceRequestTest.cs
Src/GoogleApis.Tests/Apis/Services/BaseClientServiceTest.cs
Src/GoogleApis/Apis/Services/BaseClientService.cs
Src/GoogleApis/Apis/[Media]/Upload/ResumableUpload.cs

Solve #592. Change the API of ConfigurableMessageHandler to expose an
enumerable of handlers and interceptors and NOT a list.

BaseClientService isn't thread-safe

---

Src/GoogleApis.Auth.DotNet4.Tests/OAuth2/DefaultCredentialProviderTests.cs
Src/GoogleApis.Auth.DotNet4/OAuth2/GoogleCredential.cs

Add params overload for GoogleCredential.CreateScoped

---

Src/GoogleApis.Tests/Apis/Download/MediaDownloaderTest.cs
Src/GoogleApis/Apis/[Media]/Download/MediaDownloader.cs

Three fixes related to downloads:
- Ensure query parameters are decoded properly before being re-encoded by RequestBuilder
- Handle query params without values correctly (fix index out of range error)
- Check the response code before streaming the download and report any non-success codes as failed downloaded.

Fixes for downloads

---

Src/GoogleApis.Auth.DotNet4/OAuth2/DefaultCredentialProvider.cs

Since the library is only reading from the stream it can request read-only access to it, which will make it not interfere with other tools reading the credentials file and make it possible to run on read only file systems, such as one shared on a Docker container.

Only request read access to the file when opening the stream.

---

Src/GoogleApis.Auth.DotNet4/OAuth2/GoogleWebAuthorizationBroker.cs
Src/GoogleApis.Auth/OAuth2/AuthorizationCodeInstalledApp.cs
Src/GoogleApis.Auth/OAuth2/Flows/AuthorizationCodeFlow.cs
Src/GoogleApis.Auth/OAuth2/Flows/GoogleAuthorizationCodeFlow.cs
Src/GoogleApis.Auth/OAuth2/Flows/IAuthorizationCodeFlow.cs
Src/GoogleApis.Auth/OAuth2/Requests/GoogleAuthorizationCodeRequestUrl.cs
Src/GoogleApis.Auth/OAuth2/Web/AuthorizationCodeWebApp.cs
Src/GoogleApis.Core/Apis/Http/HttpClientFactory.cs

This adds support of the library to authenticate with the [```include_granted_scopes```](https://developers.google.com/identity/protocols/OAuth2InstalledApp#incrementalAuth) parameter which [does not currently exist](http://stackoverflow.com/questions/33470699/how-to-implement-incremental-authorization-with-google-api#comment54766478_33470699).
Usage is intended to be exposed to a user of the library who is already using ```GoogleWebAuthorizationBroker.AuthorizeAsync()``` by adding a single new parameter - ```includeGrantedScopes``` - which is a nullable bool and set to null by default. For example:
```
userCredentials = await GoogleWebAuthorizationBroker.AuthorizeAsync(
MyClientSecrets, scopes, userName,
System.Threading.CancellationToken.None, new DataStore(),
true //this will set the …
```

Incremental auth support

---

Src/GoogleApis.Tests/Apis/Download/MediaDownloaderTest.cs
Src/GoogleApis.Tests/Apis/Upload/ResumableUploadTest.cs
Src/GoogleApis/Apis/[Media]/Download/MediaDownloader.cs
Src/GoogleApis/Apis/[Media]/MediaApiErrorHandling.cs
Src/GoogleApis/Apis/[Media]/Upload/ResumableUpload.cs
Src/GoogleApis/GoogleApis.csproj

This addresses issue #645.
(The majority of the change is in the tests, which were somewhat tricky.)
// cc @chrsmith @peleyal

Fix media upload/download error handling

---

Src/Support/GoogleApis.Auth/GoogleApis.Auth_Shared.shproj
Src/Support/GoogleApis.Core/GoogleApis.Core_Shared.shproj
Src/Support/GoogleApis/GoogleApis_Shared.shproj

Change MinimumVisualStudioVersion from 14.0 (VS2015) to 12.0 (VS2013).
Shared projects were introduced in Visual Studio 2013 Update 2.
Change ToolsVersion for consistency, though it shouldn't have any effect.

Adjust shared projects to work in VS2013

---

Src/Support/GoogleApis.Tests/Apis/Requests/PageStreamerTest.cs
Src/Support/GoogleApis.Tests/GoogleApis.Tests.csproj
Src/Support/GoogleApis/Apis/Requests/PageStreamer.cs
Src/Support/GoogleApis/GoogleApis_Shared.projitems

Fixes issue #632, as far as we want to for now.
This will only make the PageStreamer available - it won't be used in generated code.
We will want to add examples of how to use this.
Note that the only async option for the moment is to retrieve a whole list asynchronously.
While it would be nice to do this more lazily, that would need something like Ix-Async, and we'd prefer not to
introduce a new dependency for this at the moment.

Add PageStreamer to make it simple to fetch paged lists

---

Src/Support/GoogleApis/Apis/Requests/PageStreamer.cs

More options:
- Put this documentation into the constructor call instead
- Put this documentation into the constructor call as well
- Make this a full console app example (with a placeholder for the API key)
- Move this to documentation to https://developers.google.com/api-client-library/dotnet/get_started (maybe a new "how to"?)
Easiest to discuss the options with something concrete :)
This would complete the code part of #632.
// cc @LindaLawton @peleyal

Add an example of constructing a PageStreamer.

---

.gitmodules
GeneratedLibraries.proj
get_discovery_documents.py

This change brings in a copy of the google/apis-client-generator code used to generate per-API libraries, and wires it up with MSBuild.
The process is orchestrated by GeneratedLibraries.proj.
First, we download the discovery documents. This is isolated as its own step so we have copies of the actual discovery documents used to produce the generated libraries. This leaves the rest of the build hermetic and will help us reproduce and fix codegen problems in the future.
Next, the client generator is run on each discovery document. The generated source ends up at Src/Generated/<API PACKAGE NAME>.
Each client library project is built. The GeneratedLibraries.proj includes a list of the projects that don't currently build so they can be ignored for now.
Finally, we run NuGet to package each of …

Generate, build, and package API client libraries

---

MyGet.ps1

This PR adds a `MyGet.ps1` script file in the repository's root folder, which will be ran on the MyGet build machine.
I've confirmed that this all works, modulo a transient error where the build takes > 30 minutes and gets killed. (Publishing 141 packages can take a while.)
I'll try to get to clean a few things up, such as enabling Unit Testing as part of the build. However, it appears our Unit Tests are broken in HEAD due to the assembly load problems for `System.Net.Http.Primitives.dll`.
/cc @mmdriley

Add MyGet build support.

---

Src/Support/GoogleApis.Auth.Tests/GoogleApis.Auth.Tests.csproj
Src/Support/GoogleApis.Auth.Tests/OAuth2/Flows/GoogleAuthorizationCodeFlowTests.cs
Src/Support/GoogleApis.Auth/OAuth2/Flows/GoogleAuthorizationCodeFlow.cs
Src/Support/GoogleApis.Auth/OAuth2/Requests/GoogleAuthorizationCodeRequestUrl.cs
Src/Support/GoogleApis.Core/Apis/Requests/Parameters/ParameterUtils.cs
Src/Support/GoogleApis.Core/Apis/Util/RequestParameterAttribute.cs
Src/Support/GoogleApis.Tests/Apis/Requests/Parameters/ParameterUtilsTest.cs
Src/Support/GoogleApis.Tests/GoogleApis.Tests.csproj

Picking up where [pull 650](https://github.com/google/google-api-dotnet-client/pull/650) failed and left off prior to the big changes and my bad commits, this add the ability for users to include their own custom query parameters when making an authorization URL. This is in response to [issue 638](https://github.com/google/google-api-dotnet-client/issues/638) at request of @peleyal.
By providing a KeyValuePair<string, string>[] for the UserDefinedQueryParams member of the GoogleAuthorizationCodeFlow.Initializer, this collection will be used to update the resulting url via Google.Apis.Requests.Parameters.ParameterUtils.IterateParameters().
An attempt at a unit test has been provided with /GoogleApis.Tests/Apis/Requests/Parameters/ParameterUtilsTest.cs
The initial build will fail due to the …

Custom Auth Query Params (2)

---

Src/Support/GoogleApis.Auth/OAuth2/ServiceCredential.cs

If presenting invalid credentials in a JSON file, the Token property will be null. This reseulted in a null pointer exception at runtime. This unfortunately prevented a more meaningful RequestError "Invalid Credentials [401]" from being displayed.
Fixes issue #658.
@peleyal , would you mind reviewing this? The fix is ultra-simple. But I could use your help understanding what the `OAuth2\ServiceCredential.cs`'s `HandleResponseAsync` method does. It seems like it deserves a doc comment. I just don't know what to write.

Fix null pointer exception in HandleResponseAsync.

---

GeneratedLibraries.proj

Targets now check to see if the thing they're going to generate
already exists. If so, they don't run.
Added two new targets:
- **Regenerate** updates the discovery docs and generated code.
- **Repackage** updates the built libraries and NuGet packages.
Repackage is the new default target. It doesn't download anything or
change any files under source control, so it'll work in CI.

Add very basic incremental build to GeneratedLibraries.proj

---

GeneratedLibraries.proj

Invoking the Package target (or anything that depended on it, like the
default target Repackage) would invoke BuildProjectList before Build.
Build, in turn, is what invokes Generate, so we would try to build a
list of projects before guaranteeing the projects had actually been
generated. If Src/Generated had been deleted, BuildProjectList would
build an empty list, no projects would be built, and packaging would
fail.

Fix build ordering in GeneratedLibraries.proj

---

Src/Support/GoogleApis.Tests/Apis/Download/MediaDownloaderTest.cs
Src/Support/GoogleApis/Apis/[Media]/MediaApiErrorHandling.cs

Fixes issue #692.
(Apologies for this being necessary... I thought I'd covered all the bases in previous tests...)

Handle empty error responses in media upload/download

---

Src/Support/GoogleApis.Core/Apis/Requests/RequestBuilder.cs
Src/Support/GoogleApis.Core/Apis/Util/UriPatcher.cs
Src/Support/GoogleApis.Core/GoogleApis.Core_Shared.projitems

Fixes #636, #643.
Tested with:
`nunit3-console.exe --domain=None --framework=net-4.0 Google.Apis.Tests.dll`
I abandoned a previous approach that modified individual Uri objects in favor of a simpler and less fragile approach that makes process-wide changes. Oh well. It seems unlikely that customers writing to Google APIs are also depending on weird URL behavior.
We may need to move the call to PatchUriQuirks or make similar calls elsewhere, to ensure it anticipates all of our uses of Uri.

Add UriPatcher to fix URI quirks

---

Src/Support/CommonAssemblyInfo.cs

Otherwise the libraries built from the Net45 and Portable projects
end up with different versions and strongnames.

Fix revision number of support libraries to 0

---

Src/Support/GoogleApis.Auth.DotNet4.Tests/GoogleApis.Auth.PlatformServices.Tests_Net45.csproj
Src/Support/GoogleApis.Auth.DotNet4.Tests/packages.config
Src/Support/GoogleApis.Auth.Tests/GoogleApis.Auth.Tests.csproj
Src/Support/GoogleApis.Auth.Tests/OAuth2/BearerTokenTests.cs
Src/Support/GoogleApis.Auth.Tests/packages.config
Src/Support/GoogleApis.Core/Apis/Util/UriPatcher.cs
Src/Support/GoogleApis.Tests/Apis/Download/MediaDownloaderTest.cs
Src/Support/GoogleApis.Tests/Apis/Requests/ClientServiceRequestTest.cs
Src/Support/GoogleApis.Tests/Apis/Upload/ResumableUploadTest.cs
Src/Support/GoogleApis.Tests/GoogleApis.Tests.csproj
Src/Support/GoogleApis.Tests/packages.config
Src/Support/GoogleApis/Apis/[Media]/Download/MediaDownloader.cs
travis.sh

Today, MediaDownloader downloads content in chunks by sending one HTTP
request per chunk. Each request has an appropriate `Range` header set.
One consequence of this approach is that when users try to download
content served with `Content-Encoding: gzip` and that content happens
to be more than one chunk large, the download will fail with an error
like:
`System.IO.InvalidDataException: The magic number in GZip header is not correct. Make sure you are passing in a GZip stream.`
`HttpClientHandler` is trying to do the decoding for us because we set
its `AutomaticDecompression` property, but the decoding fails because
we've requested a range of data in the middle of a GZip stream.
Users can encounter this when downloading files from GCS that were
uploaded with `gsutil -Z`.
I considered …

Overhaul of MediaDownloader: simpler, handles `Content-Encoding: gzip`

---

Src/Support/GoogleApis.Auth.DotNet4/OAuth2/GoogleCredential.cs

ICredential is just a union of IConfigurableHttpClientInitializer and
ITokenAccess, both of which were already explicitly implemented. This
change just tidies things up.
Fixes issue #721.
// @chrisdunelm

Make GoogleCredential implement ICredential

---

Src/Support/GoogleApis.Tests/Apis/Upload/ResumableUploadTest.cs
Src/Support/GoogleApis/Apis/[Media]/Upload/ResumableUpload.cs

Fixes issue #456.
// cc @mmdriley who may be able to comment on how useful it would be to migrate the upload tests to use an HttpListener.

Propagate errors from the initial upload request more appropriately.

---

Src/Support/GoogleApis.Auth.DotNet4.Tests/GoogleApis.Auth.PlatformServices.Tests_Net45.csproj
Src/Support/GoogleApis.Auth.DotNet4.Tests/Program.cs
Src/Support/GoogleApis.Auth.DotNet4.Tests/packages.config
Src/Support/GoogleApis.Auth.Tests/GoogleApis.Auth.Tests.csproj
Src/Support/GoogleApis.Auth.Tests/Program.cs
Src/Support/GoogleApis.Auth.Tests/packages.config
Src/Support/GoogleApis.Tests/GoogleApis.Tests.csproj
Src/Support/GoogleApis.Tests/Program.cs
Src/Support/GoogleApis.Tests/packages.config
travis.sh

We change each test project from .dll to .exe and install NUnitLite,
which adds a console runner stub in Program.cs. Now running any of these
projects (right-click, "Debug", "Start New Instance"; or "Set as StartUp
Project" and F5) will actually run the tests.
Among other things, this enables easy test debugging with breakpoints!
Of course, you can still run the tests by pointing NUnit at the .exes.
For convenience, I added the "--wait" parameter in all configurations so
the console window with test results stays around.
I tried leaving the projects as .dlls and setting StartProgram, etc.
but I was unable to get that working reliably with relative paths.

Make each of the *.Tests projects runnable

---

Src/Support/GoogleApis.Tests/Apis/Upload/ResumableUploadTest.cs
Src/Support/GoogleApis/Apis/[Media]/Upload/ResumableUpload.cs

Allow a null content type for resumable uploads.

---

Src/Support/GoogleApis.Auth.WP/OAuth2/WebAuthenticationBrokerUserControl.xaml.cs

Not that sure if this happens to everyone, but I experienced crash whenever attempting OAuth in windows phone 8

Preventing OutOfRangeArgument exception when login in windows phone

---

ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/___package_name___/NetStandard/___package_name___.csproj.tmpl
ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/___package_name___/NetStandard/project.json.tmpl
ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/___package_name___/___package_name___.nuspec.tmpl

Generated libraries target netstandard1.3

---

Src/Support/GoogleApis.Auth/OAuth2/Responses/TokenResponse.cs

As it's only one property at the json response it works just fine. I've testested it one API in production and it worked like a charm.

Added 'id_token' property to TokenResponse

---

Src/Support/GoogleApis.Auth.Tests_dotnetcore/project.json
Src/Support/GoogleApis.Tests/Apis/Logging/NullLoggerTests.cs
Src/Support/GoogleApis.Tests/Apis/Requests/ClientServiceRequestTest.cs
Src/Support/GoogleApis.Tests/Apis/Services/BaseClientServiceTest.cs
Src/Support/GoogleApis.Tests/GoogleApis.Tests.csproj
Src/Support/GoogleApis.Tests_dotnetcore/project.json
run_tests_dotnetcore.bat

Enable ~100 more GoogleApis.Tests test-cases in .NET core. Tidy up project.json's. Remove unneeded Moq & Ionic.ZLib dependencies from test project. Tidy up run_tests_dotnetcore.bat.

Netcore test improvements

---

Src/Support/GoogleApis.Auth.NetStandard/project.json
Src/Support/GoogleApis.Auth.PlatformServices_Shared/OAuth2/DefaultCredentialProvider.cs
Src/Support/GoogleApis.Auth.PlatformServices_Shared/OAuth2/GoogleCredential.cs
Src/Support/GoogleApis.Auth.PlatformServices_Shared/OAuth2/ServiceAccountCredential.cs
Src/Support/GoogleApis.Auth/Google.Apis.Auth.nuspec
Src/Support/GoogleApis.Tests_dotnetcore/project.json

Due to missing cryptography platform support.

Remove ServiceAccountCredentials from netstandard

---

Src/Support/GoogleApis.Auth.DotNet4.Tests/GoogleApis.Auth.PlatformServices.Tests_Net45.csproj
Src/Support/GoogleApis.Auth.DotNet4.Tests/OAuth2/ServiceAccountCredentialTests.cs
Src/Support/GoogleApis.Auth.DotNet4.Tests/Program.cs
Src/Support/GoogleApis.Auth.DotNet4.Tests/packages.config
Src/Support/GoogleApis.Auth.NetStandard/GoogleApis.Auth.PlatformServices_NetStandard.csproj
Src/Support/GoogleApis.Auth.NetStandard/OAuth2/RsaStandard.cs
Src/Support/GoogleApis.Auth.NetStandard/Properties/AssemblyInfo.cs
Src/Support/GoogleApis.Auth.PlatformServices_Shared/OAuth2/DefaultCredentialProvider.cs
Src/Support/GoogleApis.Auth.PlatformServices_Shared/OAuth2/GoogleCredential.cs
Src/Support/GoogleApis.Auth.PlatformServices_Shared/OAuth2/ServiceAccountCredential.cs
Src/Support/GoogleApis.Auth.Tests/GoogleApis.Auth.Tests.csproj
Src/Support/GoogleApis.Auth.Tests/OAuth2/RsaTests.cs
Src/Support/GoogleApis.Auth.Tests/app.config
Src/Support/GoogleApis.Auth.Tests/packages.config
Src/Support/GoogleApis.Auth.Tests_dotnetcore/project.json
Src/Support/GoogleApis.Tests/Apis/Requests/BatchRequestTest.cs
Src/Support/GoogleApis.Tests/Apis/Upload/ImprovedResumableUploadTest.cs
Src/Support/GoogleApis.Tests_dotnetcore/project.json
SupportLibraries.proj

Support ServiceAccountCredentials in netstandard, although without initialization from X509 certificate. Fixes #797.
#805 adds tests for valid AccessToken from ServiceAccountCredential.
Fixed signing in netstandard builds so InternalsVisibleTo now works. Enabled all tests in netstandard that previously were disabled due to internal access.

NetStandard improvements

---

run_tests_dotnetcore.bat

Update run_tests_dotnetcore.bat to match run_tests_dotnetcore.sh, so both now use dotnet cli to build and test on Windows and Linux respectively

NET Core tests on Windows

---

Src/Support/GoogleApis.Auth.NetStandard/project.json
Src/Support/GoogleApis.Auth.PlatformServices_Shared/OAuth2/PromptCodeReceiver.cs
Src/Support/GoogleApis.Auth/Google.Apis.Auth.nuspec
Src/Support/GoogleApis.Auth_dotnetcore/project.json

In .NET Core prompt the user to browse to the authentication URL, rather than launch a browser. Opening a URL as a process is not supported on Core. Fixes #813

Fix PromptCodeRecevier on .NET Core

---

ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/___package_name___/project.json.tmpl
NuGet.Core.Config
Src/Generated/Google.Apis.Discovery.v1/project.json
Src/GeneratedTests/Discovery.Tests/DiscoveryTest.cs
Src/GeneratedTests/Discovery.Tests/project.json
Src/GeneratedTests/Discovery.Tests/resources/urlshortener.json
Src/Support/GoogleApis.Core/Apis/Json/NewtonsoftJsonSerializer.cs
Src/global.json
appveyor.yml
run_tests_dotnetcore.bat
run_tests_dotnetcore.sh

Fix the Google.Apis.Discovery.v1 generated library by disabling metadata property handling (ie ) in the JSON deserializer. Fixes #79
Adds a test for the Discovery generated library, for .NET Core only at the moment
Generates a project.json for all generated libraries with a netstandard build. Currently only used for the discovery test
Add the generated code test to the run_test_dotnetcore.* scripts

Fix discovery library

---

ClientGenerator/src/googleapis/codegen/languages/csharp/default/features.json
ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/___package_name___/Net45/___package_name___.csproj.tmpl
ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/___package_name___/Net45/packages.config.tmpl
ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/___package_name___/___package_name___.nuspec.tmpl
Src/Support/CommonAssemblyInfo.cs

Add a net45 target to the generated library nupkgs, which is used by net46 builds rather than the netstandard1.3 target.
This will also be used by net45 projects, but that should essentially be a no-op.
Fixes #845.

Support net46

---

ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/___package_name___/___package_name___.nuspec.tmpl
Src/Support/GoogleApis.Auth/Google.Apis.Auth.nuspec
Src/Support/GoogleApis.Core/Google.Apis.Core.nuspec
Src/Support/GoogleApis/Google.Apis.nuspec

Conform nuspec descriptions to agree exactly with the README file

Tidy up nuspec files

---

Src/Support/GoogleApis.Tests/Apis/Download/MediaDownloaderTest.cs
Src/Support/GoogleApis/Apis/[Media]/Download/MediaDownloader.cs

This is only in MediaDownloader rather than IMediaDownloader for
backward compatibility, but it can be added to the interface in v2.

Add a Range property to MediaDownloader to allow ranged downloads

---

Src/Support/GoogleApis.Auth.Tests/OAuth2/Responses/TokenResponseTests.cs
Src/Support/GoogleApis.Auth/OAuth2/Requests/TokenRequestExtenstions.cs
Src/Support/GoogleApis.Auth/OAuth2/Responses/TokenResponse.cs
Src/Support/GoogleApis.Core/Apis/Util/IClock.cs
Src/Support/GoogleApis.Tests/Apis/Http/ConfigurableMessageHandlerTest.cs
Src/Support/GoogleApis.Tests/[Mock]/MockClock.cs

This mostly concerns TokenReponse which was maintaining a local
issued time, causing issues in terms of validation around DST
transitions.
In general, we should be discouraging the use of system local time;
it's almost never appropriate, particularly when making API calls.
Unfortunately the system local time will have been persisted in JSON
in auth stores; this change avoids breaking such persisted data, by
always storing the existing property (so old code can read it) and
reading it where necessary.
Fixes #884.

Avoid using system local time anywhere

---

Src/Support/GoogleApis.Auth.DotNet4.Tests/OAuth2/GoogleCredentialTests.cs
Src/Support/GoogleApis.Auth.PlatformServices_Shared/OAuth2/DefaultCredentialProvider.cs
Src/Support/GoogleApis.Auth.PlatformServices_Shared/OAuth2/GoogleCredential.cs

Existing private `*FromJson` methods have been renamed for clarity.

Add a convenience method to obtain a GoogleCredential from a JSON string

---

NuGet.Config

This appears to be confusing AppVeyor, and we don't really need it.

Remove local directory from nuget config

---

Src/Support/GoogleApis.Tests/Apis/Upload/ImprovedResumableUploadTest.cs
Src/Support/GoogleApis/Apis/[Media]/MediaApiErrorHandling.cs
Src/Support/GoogleApis/Apis/[Media]/Upload/ResumableUpload.cs
Src/Support/GoogleApis/Apis/[Media]/Upload/ResumableUploadOptions.cs
Src/Support/GoogleApis/GoogleApis_Shared.projitems

This is a port and cleanup of some of the changes proposed in https://github.com/GoogleCloudPlatform/google-cloud-dotnet/pull/640, which will support resumable uploads using signed URLs.
Most of the changes involve a refactoring which pulls out most of `ResumableUpload<TRequest>` into a new base class: the non-generic `ResumableUpload`.

Split ResumableUpload class and introduced associated options

---

Src/Support/GoogleApis/Apis/Requests/ClientServiceRequest.cs
Src/Support/GoogleApis/Apis/[Media]/Download/MediaDownloader.cs

Upload already supports this for the initial session negotiation via ResumableUploadOptions.
(Testing this explicitly looks like more effort than it's worth - let me know if you disagree. We'll soon have integration tests in google-cloud-dotnet that would fail if the code broke...)

Allow modification of HTTP requests for download and client requests

---

Src/Support/GoogleApis.Tests/Apis/Upload/ImprovedResumableUploadTest.cs
Src/Support/GoogleApis/Apis/[Media]/Upload/ResumableUpload.cs

This is to support scenario 2a from [here](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/pull/640#issuecomment-268116549).
If/when this is merged and released, I plan to factor out the 5 lines starting from [here](https://github.com/evildour/google-cloud-dotnet/blob/master/apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/StorageClientImpl.UploadObject.cs#L66) into a public method which returns the `InsertMediaUpload` instance. Someone can then use that method to get the uploader and initiate the session without actually uploading. They can just use the resulting session URI to pass it along to some other client. I will also add a snippet demonstrating how to do this.

Expose ResumableUpload.InitiateSessionAsync

---

Src/Support/GoogleApis/Apis/[Media]/Upload/ResumableUpload.cs

This allows the inner HttpClientHandler to have auto-redirect
disabled, which makes a difference on at least some imlpementations
of .NET Core.
// cc @evildour
Fixes #930.

Use HttpClientFactory to create HttpClient in ResumableUpload

---

Src/Support/GoogleApis.Core/Apis/Http/ConfigurableMessageHandler.cs
Src/Support/GoogleApis.Core/Apis/Logging/BaseLogger.cs
Src/Support/GoogleApis.Core/Apis/Logging/ConsoleLogger.cs
Src/Support/GoogleApis.Core/Apis/Logging/ILogger.cs
Src/Support/GoogleApis.Core/Apis/Logging/LogLevel.cs
Src/Support/GoogleApis.Core/Apis/Logging/MemoryLogger.cs
Src/Support/GoogleApis.Core/GoogleApis.Core_Shared.projitems
Src/Support/GoogleApis.Core/Net45/GoogleApis.Core_Net45.csproj
Src/Support/GoogleApis.Core/NetStandard/project.json
Src/Support/GoogleApis.Core/Portable/GoogleApis.Core_Portable.csproj
Src/Support/GoogleApis.Core/Properties/AssemblyInfo.cs
Src/Support/GoogleApis.Core_dotnetcore/project.json
Src/Support/GoogleApis.Tests/Apis/Http/ConfigurableMessageHandlerTest.cs
Src/Support/GoogleApis.Tests_dotnetcore/project.json

And provide a MemoryLogger (for testing); and a simple ConsoleLogger.

Provide request/response logging

---

Src/Support/GoogleApis.Auth.DotNet4.Tests/OAuth2/GoogleCredentialTests.cs
Src/Support/GoogleApis.Auth.DotNet4.Tests/OAuth2/Pkcs8Tests.cs
Src/Support/GoogleApis.Auth.PlatformServices_Shared/OAuth2/Pkcs8.cs

According to [this answer](http://crypto.stackexchange.com/a/30616) on the cryptography StackExchange site, there is a 1 in 400 edge case where the private key's D value will only require 255 bytes to be encoded, so we were trimming it to 255 bytes, but when .NET imports the RSA key parameters, it requires them to be aligned on 8 byte boundaries apparently.
cc @iantalarico

Fix PKCS8 decoding for some RSA private keys

---

Src/Support/GoogleApis.Auth/OAuth2/Flows/GoogleAuthorizationCodeFlow.cs

Allow authorizationServerUrl and tokenServerUrl to be specified by inheriting from the Initializer.
Fixes #945

Allow custom URLs in GoogleAuthorizationCodeFlow

---

ClientGenerator/src/googleapis/codegen/api.py
ClientGenerator/src/googleapis/codegen/api_test.py
ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/___package_name___/___package_name___.cs.tmpl
ClientGenerator/src/googleapis/codegen/testdata/golden_discovery/kitchen_sink.json
Src/Generated/Google.Apis.Discovery.v1/Google.Apis.Discovery.v1.cs
Src/Generated/Google.Apis.Storage.v1/Google.Apis.Storage.v1.cs
Src/Support/GoogleApis.Tests/Apis/Requests/BatchRequestTest.cs
Src/Support/GoogleApis.Tests/[Mock]/MockClientService.cs
Src/Support/GoogleApis/Apis/Requests/BatchRequest.cs
Src/Support/GoogleApis/Apis/Services/BaseClientService.cs
Src/Support/IntegrationTests_NetCore/Google.Apis.Storage.v1.cs

Only falls back to hard-coded value if batchPath not in discovery-doc
Fixes #923. Fixes #620

Use batchPath from discovery-doc

---

Src/Support/GoogleApis.Core/Apis/Json/NewtonsoftJsonSerializer.cs
Src/Support/GoogleApis.Tests/GoogleApis.Tests.csproj
Src/Support/GoogleApis.Tests/Json/NewtonsoftJsonSerializer.cs

This allows custom settings such as turning off auto-magic date
parsing. (We need to turn this off for the BigQuery wrapper library.)
(There are some little presentation tidy-ups in the file as well; I could put those into a separate commit if you'd prefer, but they're pretty simple.)

Allow NewtonsoftJsonSerializer to be parameterized with settings.

---

Src/Support/Google.Apis.Auth.Tests/Google.Apis.Auth.Tests.csproj
Src/Support/Google.Apis.Core/Google.Apis.Core.csproj
Src/Support/Google.Apis.Tests/Google.Apis.Tests.csproj
Src/Support/Google.Apis/Google.Apis.csproj
Src/Support/IntegrationTests/IntegrationTests.csproj

This is nominally a breaking change, but Newtonsoft.Json is backward compatible across major versions in the way we use it.
Fixes #980

Update newtonsoft.json dep to latest (10.0.2)

---

Src/Support/CommonProjectProperties.xml
Src/Support/Google.Apis.Auth.Mvc/Google.Apis.Auth.Mvc.csproj
Src/Support/Google.Apis.Auth.PlatformServices/Google.Apis.Auth.PlatformServices.csproj
Src/Support/Google.Apis.Auth/Google.Apis.Auth.csproj
Src/Support/Google.Apis.Core/Google.Apis.Core.csproj
Src/Support/Google.Apis.PlatformServices/Google.Apis.PlatformServices.csproj
Src/Support/Google.Apis/Google.Apis.csproj

VS fails to load if these aren't literals in the csproj files

Fix csprojs to contain literal TargetFrameworks

---

ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/_method.tmpl

And mark as Obsolete the method that swallows all errors, and does not return status.
Fixes #982

Add download method that returns final download status

---

Src/Support/Google.Apis.Auth/OAuth2/LocalServerCodeReceiver.cs

Unregister CancellationToken, and fix exception handling on cancellation

---

ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/___package_name___/___package_name___.csproj.tmpl
README.md
Src/Support/Google.Apis.Auth/Google.Apis.Auth.csproj
Src/Support/Google.Apis.Core/Google.Apis.Core.csproj
Src/Support/Google.Apis/Google.Apis.csproj

Clarify NET Core support

---

Src/Support/Google.Apis.Auth/OAuth2/GoogleCredential.cs

Create credentials from file path; and allow scopes to be specified in all relevant credential static factory methods.
If this looks OK, I'll add xmldocs.
Helps with https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/1398

Credential improvements

---

Src/Support/Google.Apis.Core/Json/NewtonsoftJsonSerializer.cs

Commit bbab9b9 for issue #861 introduced (or rather exacerbated) a JSON serialization performance problem with specifying a list of converters via JsonSerializerSettings.
From the Json.NET performance tips (https://www.newtonsoft.com/json/help/html/Performance.htm#JsonConverters):
> There is, however, a small amount of overhead; the CanConvert method is called for every value to check whether serialization should be handled by that JsonConverter.
Before commit bbab9b9 that was only being done for RFC3339DateTimeConverter, which had a relatively quick CanConvert method.  Commit bbab9b9 added ExplicitNullConverter with a slower CanConvert method that uses reflection.  In my testing with a sizeable data set, JSON serialization was 5x slower and deserialization was 4x slower than before.
This …

Use Json.NET contract resolver to fix serialization performance issue

---

Src/Support/Google.Apis.Auth/OAuth2/LocalServerCodeReceiver.cs
Src/Support/Google.Apis.Auth/OAuth2/PromptCodeReceiver.cs
Src/Support/Google.Apis.Auth/OAuth2/ServiceCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/UserCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/Web/AuthorizationCodeWebApp.cs
Src/Support/Google.Apis.Tests/Apis/Upload/ResumableUploadTest.cs

Fixes #1089
I've verified that the issue existed on Linux before this code change, and is fixed after this code change.
The existing [`GoogleWebAuthorizationBrokerTests.cs`](https://github.com/google/google-api-dotnet-client/blob/master/Src/Support/IntegrationTests/GoogleWebAuthorizationBrokerTests.cs) integration test already covers this issue, as of #1091 (2017-09-29), but it wasn't run since on Linux.
I've now run all integration tests on Linux, and all pass.

Use correct Uri -> String method

---

Src/Support/Google.Apis.Core/Google.Apis.Core.csproj
Src/Support/Google.Apis.Core/Http/ConfigurableMessageHandler.cs
Src/Support/Google.Apis.Core/Http/HttpClientFactory.cs
Src/Support/Google.Apis.Core/Http/StreamInterceptionHandler.cs
Src/Support/Google.Apis.Core/Http/TwoWayDelegatingHandler.cs
Src/Support/Google.Apis.Tests/Apis/Download/MediaDownloaderTest.cs
Src/Support/Google.Apis.Tests/Apis/Http/GzipDeflateHandlerTest.cs
Src/Support/Google.Apis.Tests/Apis/Http/HandlerTestHelper.cs
Src/Support/Google.Apis/Download/MediaDownloader.cs
third_party/System.Net.Http/DecompressionHandler.cs
third_party/System.Net.Http/GzipDeflateHandler.cs
third_party/System.Net.Http/LICENSE.TXT
third_party/System.Net.Http/METADATA
third_party/System.Net.Http/README.md
third_party/System.Net.Http/StreamReplacingHttpContent.cs

To validate Storage hashes, we need to be able to intercept the HTTP response data before it is decompressed if the Content-Encoding is gzip. (The hash header indicates the hash of the compressed content.)
The built-in decompression in HttpClient happens too early for us, so we need to add our own decompressing HTTP handler. That's based on .NET Foundation code; the first commit of this PR adds both the original and derived works in third_party. This requires special review.
The second commit uses the decompression handler, and adds a stream interception handler which is only applied if a particular property is in the request message; this allows reasonably fine-grained control over when interception is applied.
Decompression is performed with the built-in HttpClientHandler where a) it's …

Allow response data to be intercepted before decompression

---

Src/Support/Google.Apis.Tests/ApplicationContextTests.cs

And change MockLogger, so it doesn't matter if another test running in parallel uses a MockLogger instance; this is required as the logger is global.

Re-enable logger test

---

Src/Support/Google.Apis.Auth/OAuth2/ComputeCredential.cs

This should increase the reliability of ComputeCredential.

Use the IP address of the metadata server instead of IP name

---

Src/Support/Google.Apis.Auth/OAuth2/GoogleCredential.cs

(This was creating warnings in docfx.)

Remove spurious prefix in doc comments

---

ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/___package_name___/___package_name___.csproj.tmpl

.NET SDK 2.1 introduces a problem when depending on packages that contain build tasks built with pre-VS2017 tooling.
This is a work-around which excludes the problematic tasks in legacy targets that are depending on older version of the support libraries.
See https://github.com/Microsoft/msbuild/issues/2111
I don't understand why this has only become an issue with the update to .NET SDK v2.1 from v2.0

Fix build for legacy targets after upgrade to .NET SDK 2.1

---

Src/Support/IntegrationTests/DataWrapperTests.cs

Due to a change in the translate service response

Fix data wrapper integration test

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/ServiceAccountCredentialTests.cs
Src/Support/Google.Apis.Auth/OAuth2/DefaultCredentialProvider.cs
Src/Support/Google.Apis.Auth/OAuth2/GoogleCredential.cs

@jskeet Can you see any reason not to do this? We already allow creating a `GoogleCredential` from a compute credential, and an access token.
Fixes #1282

Allow creating a GoogleCredential from a service credential

---

Src/Support/Google.Apis.Auth.AspNetCore.IntegrationTests/Controllers/HomeController.cs
Src/Support/Google.Apis.Auth.AspNetCore.IntegrationTests/Startup.cs
Src/Support/Google.Apis.Auth.AspNetCore/GoogleAuthProvider.cs
Src/Support/Google.Apis.Auth.AspNetCore/GoogleOpenIdConnectExtensions.cs

Previously this was incorrectly determining when to refresh the Google auth token using the cookie expiration time rather than the Google access-token expiration time. Now fixed. Fixes #1345

Fix bug with asp.net core auth

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/LimitedLocalhostHttpServerTests.cs
Src/Support/Google.Apis.Auth/OAuth2/LocalServerCodeReceiver.cs

Adding the ability to specify a custom set of HTML text that is shown via the LocalServerCodeReceiver upon successful OAuth authentication.
Reference Issue: https://github.com/googleapis/google-api-dotnet-client/issues/1346

Adding custom close page response for LocalServerCodeReceiver

---

Src/Support/Google.Apis.Tests/Apis/Services/BaseClientServiceTest.cs
Src/Support/Google.Apis.Tests/Google.Apis.Tests.csproj

This can only be merged after:
- Support libraries 1.40.0 have been released
- Generated libraries have been regenerated (but not necessarily released)

Add a unit test for the new Initializer.BaseUri property

---

Src/Support/Google.Apis.Core/Http/TwoWayDelegatingHandler.cs

Previous code never called Dispose() on the base DelegatingHandler, meaning the inner handler was never dispoesd of. Fixes #1399

Fix disposal of TwoWay handler

---

Src/Support/Google.Apis.Auth/OAuth2/ComputeCredential.cs

Fixes #1409
The method IsRunningOnComputeEngineNoCache checks that the metadata server returns the header Metadata-Flavor: Google. However, that endpoint will return an error if that same header is not also supplied in the request.
This means that one cannot use the default compute service account or [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity)

Added Metadata-Flavor header in request for IsRunningOnComputeEngine

---

.kokoro/BuildAndUploadSupportDocs.bat
.kokoro/BuildAndUploadSupportDocs.sh
.kokoro/BuildSupportDocs.sh
.kokoro/UploadSupportDocs.sh
DocfxFunctions.sh
Docs/README.md
Docs/docfx-1.json
Docs/docfx-2.json
Docs/index.md

The scripts are all within the .kokoro directory to avoid confusion with the regular release process. Eventually we'd probably want to move them.

Initial support for docfx: building and uploading support documentation

---

.kokoro/BuildGeneratedDocs.sh
.kokoro/BuildSupportDocs.sh
Docs/index.md

This is needed because Google.Apis.Core is the name of a package, but it doesn't contain a Google.Apis.Core namespace.

Allow the "entry namespace" in index.md to vary from the package name

---

Src/Support/Google.Apis.Tests/Apis/Upload/ResumableUploadTest.cs
Src/Support/Google.Apis/Upload/ResumableUpload.cs

Note: no tests, as we're trying to obtain the same behavior in a safer way. Trying to test that we don't affect the client would be really painful.
I *did* check that after I'd removed the "attach to the HttpClient" and before I'd added the "attach to the request", the tests failed.

Fix upload request handling

---

ClientGenerator/src/googleapis/codegen/languages/csharp/default/features.json
Src/Support/CommonProjectProperties.xml

Reverts googleapis/google-api-dotnet-client#1445, which itself reverted #1443.
The issues have been resolved server-side, so we're now okay to go ahead with this.

Reapply "Update version v1.40.3 -> v1.41.0"

---

Src/Support/Google.Apis.Tests/Apis/Upload/ResumableUploadTest.cs
Src/Support/Google.Apis/Upload/ResumableUpload.cs

Fixes #1449
(I considered changing the while loop to a do/while loop with the same condition, but I wasn't able to *easily* reason about whether LastMediaLength might already be ChunkSize + 1.)

Fix handling of disposed streams

---

Src/Support/Google.Apis.Tests/Apis/Services/BaseClientServiceTest.cs
Src/Support/Google.Apis/Services/BaseClientService.cs

Fixes #1453
(We should wait for verification that my intuition was correct on #1453 before releasing a new version though.)

Clone VersionHeaderBuilder before modifying it in BaseClientService

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/Flows/AuthorizationCodeFlowTests.cs
Src/Support/Google.Apis.Auth/OAuth2/Flows/AuthorizationCodeFlow.cs

Previously, using an initializer with Scopes set to null would crash
when CreateAuthorizationCodeRequest() was called. Now, the null Scopes
propogates safely through as a null Scope for AuthorizationCodeRequestUrl.
This is necessary because some OAuth sites do not recognize the "scope"
parameter and will return an error instead of the authorization token if
the URL contains it.
I have updated the tests and added one for the default authorization
code request.

Allow null Scopes

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/Flows/AuthorizationCodeFlowTests.cs
Src/Support/Google.Apis.Auth/OAuth2/Flows/AuthorizationCodeFlow.cs

I added the same check and a test for ExchangeCodeForTokenAsync() in the second CL.

Allow null Scopes in ExchangeCodeForTokenAsync()

---

BuildSupport.sh

I don't understand why this is now required. I'll investigate further once we're successfully releasing again.

Include a build in the pack stage of building support libraries

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/GoogleCredentialTests.cs
Src/Support/Google.Apis.Auth/OAuth2/AccessTokenWithHeaders.cs
Src/Support/Google.Apis.Auth/OAuth2/JsonCredentialParameters.cs

- Changes the JSON var name for quota project from `quota_project` to `quota_project_id`.
- Adds a public constructor to `AccessTokenWithHeaders`, mainly to be used for testing purposes outside of `Google.Apis.Auth`

Minor changes to quota project as a header related code.

---

Src/Support/Google.Apis.Auth/OAuth2/GoogleCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/RequestExtensions.cs
Src/Support/Google.Apis.Auth/OAuth2/ServiceCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/UserCredential.cs
Src/Support/Google.Apis.Core/Http/ConfigurableMessageHandler.cs
Src/Support/Google.Apis/Requests/ClientServiceRequest.cs
Src/Support/IntegrationTests/PerCallAuthTests.cs

I prefer this one to #1512 but still I'm not oh so happy. I've tried to change as least as possible, and this is the best I can come up with. Ideas are more than welcome.
If we were to take a `Google.Apis.Auth` dependency on `Google.Apis` and `Google.Apis.Core`, we can expect the credentials to be `ICredential` instead of `IHttpExecuteInterceptor`, but I think that anyway, they need to be `IHttpExecuteInterceptor` so no real advantage to that.
The integration tests are the same in both PRs.

Fixes service/call credential clashes in REST clients.

---

BuildGenerated.sh
PostGeneration/admob_v1.sh

The first API to need this is AdMob V1.
This fixes #1507 - or at least, will when the API is next published.
(That will be either when the minor version is bumped, or when the
API discovery doc changes. It would be relatively tricky to "force"
a change here.)
We don't want to do much per-API work, but tiny little tweaks like
this provide a lot of value for little work.

Allow post-generation tweaks on a per-API basis

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/ComputeCredentialTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/GoogleCredentialTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/OidcTokenFakes.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/OidcTokenOptionsTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/OidcTokenTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/ServiceAccountCredentialTests.cs
Src/Support/Google.Apis.Auth/JsonWebToken.cs
Src/Support/Google.Apis.Auth/OAuth2/ComputeCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/GoogleAuthConsts.cs
Src/Support/Google.Apis.Auth/OAuth2/GoogleCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/IOIdCTokenProvider.cs
Src/Support/Google.Apis.Auth/OAuth2/OIdCToken.cs
Src/Support/Google.Apis.Auth/OAuth2/OIdCTokenFormat.cs
Src/Support/Google.Apis.Auth/OAuth2/OIdCTokenOptions.cs
Src/Support/Google.Apis.Auth/OAuth2/ServiceAccountCredential.cs
Src/Support/Google.Apis.Core/Util/Utilities.cs

@bshaffer Please confirm that this is what's requiered.
- Is there some way in which I could test that the tokens are as expected?
- For user credentials (4th commit) I got from your document that the same token used for everything else is a valid OIDC token, is this correct?
- Is target audience then not used for user credentials when generating the OIDC token?
- We still don't support impersonation credentials, but when I get to #1312 I'll make sure they are implementes as an OIDC token provider as well.
@jskeet I think this is the cleanest I could manage, tried several things. Take a look now or wait till we hear from @bshaffer as you prefer.
@salrashid123 FYI.

OIDC Token emission support

---

Src/Tools/DiscoveryDocPatcher/Program.cs

The Games discovery doc no longer has the deprecated enum values.
(cc @amanda-tarafa)

Remove Games patching

---

Src/Tools/DiscoveryDocPatcher/Program.cs

I'd been confused by what I saw when coming up with the previous
commit. A new enum value has been added *before* playedWith, and the
description has been changed too.
I'll investigate internally in terms of whether inserting a new enum
value is expected to be okay.
(Currently running the full build to check it works...)

Reinstate Games patching, but fix it.

---

global.json

Hope this is OK, since I unistalled all but one patch of each minor version of the SDK, I've been changing this by hand locally on each branch and reverting after.

Changes to global.json so that the SDK version rolls forwards at the minor version.

---

Src/Support/Google.Apis.Tests/Apis/Requests/ClientServiceRequestExtensionsTest.cs
Src/Support/Google.Apis/Requests/ClientServiceRequestExtensions.cs
Src/Support/IntegrationTests/StorageApiTests.cs

I'd want to write a few unit tests and then documentation.
The integration test shows how this can be used, including a
demonstration of "initialize request, set a property, execute the
request" all within a single expression.
It's unfortunate that this has to be an extension method, but that's
the only way to get the type inference working appropriately.
This is an alternative approach to the feature request in #1562.

Extension method for requests to allow fluent configuration

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/BearerTokenTests.cs
Src/Support/Google.Apis.Auth/OAuth2/BearerToken.cs
Src/Support/IntegrationTests/PerCallAuthTests.cs

Because of https://developers.google.com/identity/protocols/oauth2/index.html#4.-send-the-access-token-to-an-api.

Marks as Obsolete Google.Apis.Auth.OAuth2.BearerToken.QueryParameterAccessMethod.

---

Src/Support/Google.Apis.Auth.Tests/GoogleJsonWebSignatureTests.cs
Src/Support/Google.Apis.Auth.Tests/JsonWebSignatureTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/ComputeCredentialTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/GoogleCredentialTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/OidcTokenTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/Responses/TokenResponseTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/ServiceAccountCredentialTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/TokenRefreshManagerTests.cs
Src/Support/Google.Apis.Auth.Tests/SignedTokenVerificationOptionsTests.cs
Src/Support/Google.Apis.Auth.Tests/SignedTokenVerificationTests.cs
Src/Support/Google.Apis.Tests/Apis/Http/ConfigurableMessageHandlerTest.cs
Src/Support/Google.Apis.Tests/Mocks/MockClock.cs
Src/Support/IntegrationTests/StorageApiTests.cs

- Accept a DateTime on construction; most code set it immediately anyway
- Don't allow it to be constructed *without* an explicit initial time, so it's always clear what it will be
- Forbid use of the deprecated Now property

Simplify MockClock creation

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/GoogleCredentialTests.cs
Src/Support/Google.Apis.Auth/OAuth2/ComputeCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/DefaultCredentialProvider.cs
Src/Support/Google.Apis.Auth/OAuth2/GoogleCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/IGoogleCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/ServiceAccountCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/ServiceCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/UserCredential.cs
Src/Support/Google.Apis.Core/Http/ConfigurableMessageHandler.cs
Src/Support/Google.Apis.Tests/Apis/Http/ConfigurableMessageHandlerTest.cs

In preparation for having the credential be the source of truth for quota project client options.
Client builders (gRPC and Rest) can now use the credential as a proxy for setting the quota project and can fail if a quota project is set in combination with an already built credential.
I'm uncertain about the second commit though (I have a similar one for the gRPC side). Rigorously speaking it is necessary or else we might end up sending two quota projects. But it seems like a terrible hack, an awful place to fail, and it would be breaking for anyone setting the quota project through interceptors right now, althouhg that is highly unlikely because the backend is not doing much with it. I'm happy to split this PR in two if we want to think more about the second commit.

With quota project

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/AccessTokenWithHeadersTests.cs
Src/Support/Google.Apis.Auth/OAuth2/AccessTokenWithHeaders.cs
Src/Support/Google.Apis.Auth/OAuth2/GoogleCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/ServiceCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/UserCredential.cs

So it can be reused from GAX for supporting quota project as an extensible client option.

Makes AccessTokenWithHeaders more usable from outside its package.

---

Src/Tools/DiscoveryDocPatcher/Patcher.cs
Src/Tools/DiscoveryDocPatcher/Program.cs

Required because `admin_directory_v1.json` no longer exists.
Making this change, rather than simply removing the relevant patch, just in case it re-appears at some point.

Make discovery-doc patcher a little more robust

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/LimitedLocalhostHttpServerTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/LocalServerCodeReceiverTests.cs
Src/Support/Google.Apis.Auth/OAuth2/LocalServerCodeReceiver.cs
Src/Support/IntegrationTests/LocalServerCodeReceiverTests.cs

As always, one commit at a time is best.
* One of the tests on the first commit shows a couple of issues with the existing implementation and why our current tests didn't catch #1596 at least on affected environments.
* The first 3 commits fix those issues, after those, our integration tests catch #1596 
* The 4th commit makes the choosing of the local callback URL configurable as agreed offline.
* The 5th commit fixes #1596

Improvements and fixes to LocalServerCodeReceiver.

---

ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/___package_name___/___package_name___.cs.tmpl
Src/Generated/Google.Apis.Translate.v2/Google.Apis.Translate.v2.cs

- Spaces at the start and end
- Comma at the end
This makes it easier to reproduce in the C# generator.
This commit also regenerates all APIs - which only changes Translate v2 as that's the only API to include any features (in the Discovery doc sense).

Change formatting of the feature list array

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/OidcTokenFakes.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/Responses/TokenResponseTests.cs
Src/Support/Google.Apis.Auth/OAuth2/ComputeCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/GoogleAuthConsts.cs
Src/Support/Google.Apis.Auth/OAuth2/Responses/TokenResponse.cs

Unfortunately ComputeTokenUrl is public, so we can't guarantee at
compile-time that we're not using that anywhere else, but I've
checked it via search in Visual Studio.
I haven't added any tests, but I'm happy to do so if you'd like. Suggestions for *what* you'd like to see tests for would be welcome...

Use the GCE_METADATA_HOST environment variable for all metadata access

---

Src/Support/Google.Apis.Auth.AspNetCore3.IntegrationTests/ClientInfo.cs
Src/Support/Google.Apis.Auth.AspNetCore3.IntegrationTests/Controllers/HomeController.cs
Src/Support/Google.Apis.Auth.AspNetCore3.IntegrationTests/Google.Apis.Auth.AspNetCore3.IntegrationTests.csproj
Src/Support/Google.Apis.Auth.AspNetCore3.IntegrationTests/Program.cs
Src/Support/Google.Apis.Auth.AspNetCore3.IntegrationTests/Startup.cs
Src/Support/Google.Apis.Auth.AspNetCore3.IntegrationTests/Views/Home/ForceTokenRefresh.cshtml
Src/Support/Google.Apis.Auth.AspNetCore3.IntegrationTests/Views/Home/ForceTokenRefreshCheckPersisted.cshtml
Src/Support/Google.Apis.Auth.AspNetCore3.IntegrationTests/Views/Home/Index.cshtml
Src/Support/Google.Apis.Auth.AspNetCore3.IntegrationTests/Views/Home/Login.cshtml
Src/Support/Google.Apis.Auth.AspNetCore3.IntegrationTests/Views/Home/Logout.cshtml
Src/Support/Google.Apis.Auth.AspNetCore3.IntegrationTests/Views/Home/ScopeListing.cshtml
Src/Support/Google.Apis.Auth.AspNetCore3.IntegrationTests/Views/Home/ShowTokens.cshtml
Src/Support/Google.Apis.Auth.AspNetCore3.IntegrationTests/Views/Home/StorageBucketListing.cshtml
Src/Support/Google.Apis.Auth.AspNetCore3.IntegrationTests/Views/Home/Translate.cshtml

So it can be better used as sample code showing Google.Apis.Auth.AspNetCore3 usage.
Once this is in I'll add a README and update the docs.
Towards #1584 .

Cleans up and makes Google.Apis.Auth.AspNetCore3.IntegrationTests clearer.

---

Src/Support/Google.Apis.Auth.AspNetCore3/Google.Apis.Auth.AspNetCore3.csproj

- These weren't being used, just leftovers.

Cleans ASP.NET Core 2 dependencies from Google.Apis.Auth.AspNetCore3 .csproj.

---

Src/Tools/DiscoveryDocPatcher/Patcher.cs
Src/Tools/DiscoveryDocPatcher/Program.cs

This just increases the length of one parameter description by adding spaces so that text wrapping doens't interfere with EOL markers when generating.

Patches DataLabeling V1Beta1 discovery doc.

---

Src/Support/Google.Apis.Core/Requests/Parameters/ParameterValidator.cs
Src/Support/Google.Apis.Tests/Apis/Requests/Parameters/ParameterValidatorTest.cs
Src/Support/Google.Apis/Requests/ClientServiceRequest.cs

I have added more information to validation failure exceptions generated by ClientServiceRequest.AddParameters()
This is an attempt at the following issue #1704

Add more information to parameter validation failures.

---

Src/Tools/DiscoveryDocPatcher/Program.cs

Release is failing because the bits that we were patching have changed. But I won't fix the patcher until we are back generating this API (there's an internal issue), the discovery doc might continue to change until then.

ci: Stops patching admin_directory_v1.json which we are not generating anyway.

---

Src/Support/Google.Apis.Tests/Apis/Requests/ClientServiceRequestTest.cs
Src/Support/Google.Apis/Requests/ClientServiceRequest.cs
Src/Support/Google.Apis/Services/BaseClientService.cs

This only allows the validation of patterns to be bypassed - required parameters still have to be provided.
Workaround for #1729.

Allow parameter validation to be bypassed

---

Src/Support/IntegrationTests/DataWrapperTests.cs

This is to account for slightly different results that we get ocasionally.

test: Loosens a couple of translation tests.

---

Src/Tools/DiscoveryDocPatcher/Program.cs

The patch is not needed with the new Microgenerator since we were fixing a problem with text wrapping in XML docs.

chore: Stops patching Data Labeling.

---

Src/Support/Google.Apis.Tests/Apis/Requests/BatchRequestTest.cs
Src/Support/Google.Apis/Requests/BatchRequest.cs
Src/Support/Google.Apis/Services/BaseClientService.cs

This is for consideration. The hoops I'm jumping throuhg is so as not to break anyone that relied on the HttpRequestException and its message format which unfortunately is the only way they could had been obtaining the HttpStatusCode.
I considered calling EnsureSuccessStatusCode() before anything, but that will dispose of the content if there's an error, so we cannot later parse the RequestError.
I know this is ugly, but something like this would be very useful for diagnosing batch issues, where the issues are not with the individual requests contained in the batch bot with the batch request itself. See https://github.com/googleapis/google-api-dotnet-client/issues/1619#issuecomment-680051653 for instance.
If you are fine with this, I'll add tests, etc.

feat: Include the response content on the exception thrown by a batch request.

---

DocfxFunctions.sh

Looks like older versions of docfx didn't like .NET Core SDK 3.1 (or
minor updates to it)

Fix docfx build

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/ComputeCredentialTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/Flows/AuthorizationCodeFlowTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/Flows/GoogleAuthorizationCodeFlowTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/ImpersonatedCredentialTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/ServiceAccountCredentialTests.cs
Src/Support/Google.Apis.Auth/OAuth2/AccessTokenCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/ComputeCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/Flows/AuthorizationCodeFlow.cs
Src/Support/Google.Apis.Auth/OAuth2/Flows/GoogleAuthorizationCodeFlow.cs
Src/Support/Google.Apis.Auth/OAuth2/Flows/IHttpAuthorizationFlow.cs
Src/Support/Google.Apis.Auth/OAuth2/GoogleCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/IGoogleCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/ImpersonatedCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/ServiceAccountCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/ServiceCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/UserCredential.cs
Src/Support/Google.Apis.Core/Http/HttpClientFactory.cs
Src/Support/Google.Apis.Tests/Apis/Http/HttpClientFactoryTest.cs

Closes #1547
@jskeet a proposal to allow setting a proxy on GoogleCredential. Once we've agreed, I'll add the tests I can (probably unit only).

feat: Allows specifying a proxy on a GoogleCredential.

---

.github/renovate.json

I'd forgotten that JSON prohibits trailing commas (many libraries
permit it, and it makes for cleaner diffs).
Fixes #1932
Additionally, let's not trigger Renovate PRs on weekends.

chore: Fix Renovate configuration

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/TokenRefreshManagerTests.cs
Src/Support/Google.Apis.Auth/OAuth2/TokenRefreshManager.cs

The new test (almost) never passed before making the changes in `TokenRefreshManager` and is always green after.

fix: Observes exceptions in refresh token tasks

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/LocalServerCodeReceiverTests.cs
Src/Support/Google.Apis.Auth/OAuth2/LocalServerCodeReceiver.cs

LocalServerCodeReceiver uses a best-effort mechanism
to open a browser. This behavior might not be appropriate
in all environments. Allow deriving classes to override
the method to customize the behavior.

Allow deriving classes to override OpenBrowser

---

Src/Support/CommonProjectProperties.xml
features.json

Features
- [#2067] BREAKING. Improve error handling for failed requests.
BREAKING CHANGE: If calling code depended on exact GoogleApiException message or string representation.
- [#2086] Makes `LocalServerCodeReceiver` partially extendable.

Update version: 1.56.0 -> 1.57.0

---

.github/renovate.json
Src/Support/Google.Apis.Auth.Tests/Google.Apis.Auth.Tests.csproj
Src/Support/Google.Apis.Tests/Google.Apis.Tests.csproj
Src/Support/IntegrationTests/IntegrationTests.csproj

It dropped support for frameworks we still target.
This reverts #2113

ci: Stop updating xunit.runner.visualstudio.

---

DocfxFunctions.sh

I suspect that installing .NET 6 on the CI machine caused the
previous version of docfx to fail. (It's always been somewhat picky
about SDK versions.)

chore: Update docfx to 2.59.2

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/DefaultCredentialProviderTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/UrlSourcedExternalAccountCredentialTest.cs
Src/Support/Google.Apis.Auth/OAuth2/DefaultCredentialProvider.cs
Src/Support/Google.Apis.Auth/OAuth2/ExternalAccountCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/JsonCredentialParameters.cs
Src/Support/Google.Apis.Auth/OAuth2/Requests/StsRequestTokenBuilder.cs
Src/Support/Google.Apis.Auth/OAuth2/Requests/StsTokenRequest.cs
Src/Support/Google.Apis.Auth/OAuth2/Requests/StsTokenRequestExtensions.cs
Src/Support/Google.Apis.Auth/OAuth2/ServiceCredential.cs

FYI: @lsirac, @jpassing, @moserware

feat: Add support for Workforce Identity Pools external credentials.

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/DefaultCredentialProviderTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/ExternalAccountCredentialTestsBase.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/FileSourcedExternalAccountCredentialTest.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/UrlSourcedExternalAccountCredentialTest.cs
Src/Support/Google.Apis.Auth/OAuth2/DefaultCredentialProvider.cs
Src/Support/Google.Apis.Auth/OAuth2/ExternalAccountCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/FileSourcedExternalAccountCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/JsonCredentialParameters.cs
Src/Support/Google.Apis.Auth/OAuth2/UrlSourcedExternalAccountCredential.cs

Towards #2033.
Also refactors the existing external account credential tests to make it easier to reuse test code.
FYI: @lsirac, @jpassing , @moserware

feat: Add support for file-sourced external credentials.

---

Src/Support/Google.Apis.Auth/OAuth2/DefaultCredentialProvider.cs
Src/Support/Google.Apis.Auth/OAuth2/GoogleAuthConsts.cs
Src/Support/Google.Apis.Auth/OAuth2/GoogleCredential.cs

- If set, the value on the environment variable is always applied to ADC.
- A helper method is provided to apply this value to any credential.

feat: Supports environment variable quota project ID.

---

Src/Support/CommonProjectProperties.xml

Features
- #2228 Supports Quota Project environment variable for ADC.
- #2219 Removes obsolete OOB code. BREAKING CHANGE: We have removed OOB support from the library because the feature is not supported by Google OAuth as of October 3rd 2022. See the [official announcement](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#disallowed-oob) for more information.
- #2216 Log errors when trying to reach Compute's metadata server.
- #2177, #2197, #2200, #2206, #2215, #2235 Support for Workload Identity Federation and Worforce Identity Federation.
- #2103 Compute credentials support explicit scopes.
- #2096 Improves deserialization error handling.

Update support version: 1.57.0 -> 1.58.0-beta01

---

Src/Support/CommonProjectProperties.xml

Bug fixes:
- #2251 Which fixes a typo on then name of one of the AWS Credential environment variables.
- #2264 Which adds a missing line break in AWS Credential canonical request.
Features
- #2269 Support per-request max retry configuration.

Update support version: 1.58.0-beta01 -> 1.58.0-beta02

---

Src/Support/Google.Apis.Tests/Apis/Requests/BatchRequestTest.cs
Src/Support/Google.Apis/Requests/BatchRequest.cs

Fixes #2272.
(Most changes are just reformatting/modernizing; they're in a first commit.)

fix: Don't attempt to use an empty/null media type in batch responses 

---

CSharpGeneratorFunctions.sh
Src/Support/CommonProjectProperties.xml
features.json

And support version: 1.58.0-beta02 => 1.58.0
Dependencies:
- Client libraries no longer target netstandard1.0 or net40.
Bug fixes:
- #2273 Don't attempt to use an empty/null media type in batch responses
- #2251 Which fixes a typo on then name of one of the AWS Credential environment variables.
- #2264 Which adds a missing line break in AWS Credential canonical request.
Features
- #2269 Support per-request max retry configuration.
- #2228 Supports Quota Project environment variable for ADC.
- #2219 Removes obsolete OOB code. BREAKING CHANGE: We have removed OOB support from the library because the feature is not supported by Google OAuth as of October 3rd 2022. See the [official announcement](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#disallowed-oob) for more …

Update version: 1.57.0 => 1.58.0

---

Src/Support/Google.Apis.Tests/Apis/Upload/ResumableUploadTest.cs
Src/Support/Google.Apis.Tests/Mocks/MockClientService.cs

This also stops ignoring write errors in HttpListener. I don't know why we used to ignore them, but it made it harder to diagnose the problem here.

chore: Improve HttpListener-based test reliability

---

Src/Support/Google.Apis/Requests/VersionHeaderBuilder.cs

This is equivalent to googleapis/gax-dotnet/pull/637

fix: Drop trailing hex characters from version header values

---

.kokoro/BuildSupportDocs.sh

This avoids inaccurate redirects.
(We're trying to avoid duplicating content between googleapis.dev and cloud.google.com. This is slightly awkward for a number of reasons, but this change at least improves the user experience for now.)

chore: Use cloud.google.com as the target for support libraries

---

Src/Support/CommonProjectProperties.xml
features.json

And support libraries from 1.59.0-alpha01 => 1.59.0
Features:
- #2308 ComputeCredential implements IBlobSigner

Update version: 1.58.0 => 1.59.0

---

CSharpGeneratorFunctions.sh

This uses SPDX license expressions instead of the PackageLicenseFile property.
Fixes #2359 in terms of manual changes.
(We'll then need to wait for libraries to be regenerated and roll out organically.)

feat: Update to generator v1.4.12

---

BACKLOG.md

We now support System.Net.Http.IHttpClientFactory which allows to configure HttpClient to use Polly among other things.

chore: Remove #1414 from the Backlog as obsolete

---

.github/workflows/build.yml

We are getting brownout errors because action support for Ubuntu 18.04 will be fully deprecated on April 1st 2023.
See https://github.com/actions/runner-images/issues/6002

ci: Several improvements to the build GitHub action.

---

Src/Support/Google.Apis.Auth/OAuth2/DefaultCredentialProvider.cs

This link is included in the exception message if ADC is requested and is not setup.
This change has been requested by the Auth TW team.

fix: Change the link to ADC documentation

---

BuildGenerated.sh

Fixes #2384
We don't need to force regeneration - I've delisted the latest Admin Discovery package (which is the only one we patch now), and the only changes were in comments, so we can just wait for the next time it's regenerated normally.

fix: Only generate .json files, not .json.original files

---

.kokoro/gcp_windows_docker/Dockerfile

And make choco install less verbose.

ci: Use chocolatey to install .NET Core 3.1

---

Src/Support/Google.Apis.Core/Util/Utilities.cs
Src/Support/Google.Apis.Tests/Apis/Utils/UtilitiesTest.cs

Movement towards #2040, but doesn't finish fixing it yet.

feat: Utility methods to support google-datetime format (and eventually others)

---

FAQ.md
README.md

(We could potentially put the maintenance mode part in the libraries help page as well, but I think it might be better to keep that on GitHub. Likewise we don't need the Unity/Xamarin/etc support on the REST-specific help page as it's in the supported platforms doc.)

docs: Direct users to new REST libraries help page instead of the FAQ

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/Flows/AuthorizationCodeFlowTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/Pkcs8Tests.cs
Src/Support/Google.Apis.Tests/Apis/Download/MediaDownloaderTest.cs
Src/Support/Google.Apis.Tests/Apis/Http/ConfigurableMessageHandlerTest.cs
Src/Support/Google.Apis.Tests/Apis/Requests/BatchRequestTest.cs
Src/Support/Google.Apis.Tests/Apis/Requests/ClientServiceRequestTest.cs
Src/Support/Google.Apis.Tests/Apis/Requests/PageStreamerTest.cs
Src/Support/Google.Apis.Tests/Apis/Services/BaseClientServiceTest.cs
Src/Support/Google.Apis.Tests/Apis/Upload/ResumableUploadTest.MultiChunk.cs
Src/Support/Google.Apis.Tests/Apis/Utils/ExponentialBackOffTest.cs
Src/Support/Google.Apis.Tests/Mocks/MockMessageHandler.cs
Src/Support/IntegrationTests/GoogleJsonWebSignatureTests.cs
Src/Support/IntegrationTests/ServiceAccountTests.cs
Src/Support/IntegrationTests/StorageApiTests.cs

These were mostly prompted by new xUnit warnings, but then looking at the number of calls to Task.Result and typos in the name "configuredHandler" prompted the rest of the changes.
There's plenty we could still do to improve the tests, but this is at least a significant improvement.

tests: Test refactoring

---

Src/Support/Google.Apis.Auth/OAuth2/GoogleCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/IGoogleCredential.cs
Src/Support/Google.Apis.Core/Google.Apis.Core.csproj
Src/Support/Google.Apis.Core/Http/HttpExtenstions.cs
Src/Support/Google.Apis.Core/Http/InterceptorDelegatingHandler.cs
Src/Support/IntegrationTests/HttpClientWithExecuteInterceptorTests.cs

This is a proposed plan for #2450
Lacking documentation and tests right now...
(Basically, this is all simple if folks have a concrete credential, as they all either implement IHttpExecuteInterceptor, or can do so very simply, such as GoogleCredential.)

feat: Add extension method for IHttpExecuteInterceptor to create a DelegatingHandler

---

.kokoro/autorelease.sh

- Include a user.email for CLA.
- Have git ignore chmod.
This is accompanied by an internal CL.

fix: Fixes for Apiary autorelease.

---

.kokoro/autorelease.sh

These currently break the build. Once we've fixed the build, we can look at fixing these two APIs.

chore: Skip PolicySimulator v1alpha and v1beta

---

.kokoro/BuildGeneratedDocs.sh
PostGeneration/cloudsupport_v2.sh
Src/Generated/Google.Apis.CloudSupport.v2/Google.Apis.CloudSupport.v2.cs

We might want to change the generator to just strip backticks - but we'll proceed cautiously. A fuller fix is likely to involve a Discovery doc change to preserve line breaks.

fix: Fix documentation generation

---

Src/Support/Google.Apis.Auth.Tests/Google.Apis.Auth.Tests.csproj
Src/Support/Google.Apis.Auth.Tests/OAuth2/Flows/AuthorizationCodeFlowTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/GoogleCredentialTests.cs

We only used it in a couple of Auth tests, and given our fairly old set of test targets (which are fiddly to change), it's simplest just to create fakes for those tests.

chore: Remove Moq

---

BuildGenerated.sh

This effectively rollbacks https://github.com/googleapis/google-api-dotnet-client/pull/2496/commits/6611c9691157e4aea277e514623f4bb0f99f3a37 to allow for the use case where:
- We first download.
- We revert changes that are not relevant for generation, like revision only changes.
- We generate what remains.
For instance, the latest release took a long time because it generated and attempted to push everything. No harm done as Nuget won't allow pushing the same package twice, but it is still clearer (for diagnosing failed releases and for quota purposes) to only generate and push what has changed.

ci: Allow skipdownload to only generate changes

---

Src/Support/CommonProjectProperties.xml
features.json

Updates support version: 1.61.0 -> 1.61.1
Bugs:
* [#2506](https://github.com/googleapis/google-api-dotnet-client/pull/2506) Which uses the invariant culture to convert DateTimeOffset.
Features:
* [#2453](https://github.com/googleapis/google-api-dotnet-client/pull/2453) Which adds an extension method for IHttpExecuteInterceptor to create a DelegatingHandler

Update version: 1.61.0 -> 1.61.1

---

features.json

(See https://github.com/googleapis/gapic-generator-csharp/pull/465 for removal of usage in the generator.)

chore: Remove configuration for features which are no longer used

---

Src/Support/Google.Apis.Tests/Json/NewtonsoftJsonSerializerTest.cs

This PR is a companion of https://github.com/googleapis/gapic-generator-csharp/pull/680.

tests: Add tests for serializing and deserializing case sensitive JSON.

---

Src/Support/Google.Apis.Auth/OAuth2/Responses/TokenResponse.cs

Corrected spelling of "doesn't"

docs: Fix typo in TokenResponse XML docs

---

features.json

Note this just changes the version number for the next releases, but the libraries were already going to be generated using v1.62.1 support libraries.

chore: Update generated library versions to be 1.62.1

---

.config/dotnet-tools.json

I've run full doc generation, and it appears to be okay.

chore: Upgrade docfx to 2.71.0

---

Src/Support/Google.Apis.Auth/Google.Apis.Auth.csproj
Src/Support/Google.Apis.Auth/OAuth2/ComputeCredential.cs

Closes #2475 
@jskeet a few comments on this one:
- The first commit is the implementation for Linux which is more or less straightforward.
- The second commit is the implementation for Windows, checking against Windows Management Instrumentation and not the Registry. Checking against WMI is what's recommend internally.
I'm happy to rewrite the second commit using reflection so we don't need the extra System.Management dependency, but then we'd have to ask users to include the dll themselves as we cannot add it conditionally on OS, or at least I haven't found how to do that.

feat: Check BIOS for determining GCE residency.

---

Src/Support/Google.Apis.Auth.AspNetCore.IntegrationTests/Google.Apis.Auth.AspNetCore.IntegrationTests.csproj
Src/Support/Google.Apis.Auth.AspNetCore3.IntegrationTests/Google.Apis.Auth.AspNetCore3.IntegrationTests.csproj
Src/Support/Google.Apis.Auth.AspNetCore3/Google.Apis.Auth.AspNetCore3.csproj
Src/Support/Google.Apis.Auth.PlatformServices/Google.Apis.Auth.PlatformServices.csproj
Src/Support/Google.Apis.Auth.Tests/Google.Apis.Auth.Tests.csproj
Src/Support/Google.Apis.Auth/Google.Apis.Auth.csproj
Src/Support/IntegrationTests/IntegrationTests.csproj

This is the sort of internal version of #2596 - but this only fixes the support build, not applications depending on the auth library.

chore: Suppress warning for System.CodeDom on older frameworks

---

Src/Support/Google.Apis.Core/Util/DiscoveryFormat.cs
Src/Support/Google.Apis.Tests/Apis/Utils/DiscoveryFormatTest.cs

Needs tests - this is primarily for quick validation/review.
Originally, I had considered putting *all* the conversion code into this class, including to DateTime and Object... but then reconsidered.
As this now handles only DateTimeOffset, perhaps we should actually just put the code in Utilities after all? We'd change the behavior of GetDateTimeOffsetFromString and GetStringFromDateTimeOffset - probably to match the "google-datetime" behavior - and then add corresponding methods for the "date-time" format.
Or we could just leave Utilities alone entirely (deprecating the methods above at some point after changing the generator) and only include this new code. Thoughts welcome.

feat: Introduce a new class for handling Discovery format

---

.config/dotnet-tools.json

The bug that affects google-cloud-dotnet doesn't affect this repo, due to the configuration we're using.
(I'm not sure why I didn't create this PR at the time...)
docfx has moved on since this anyway, but it would be good to be consistent between this and google-cloud-dotnet.

chore: Update docfx to 2.71.1

---

Src/Support/Google.Apis.Core/Json/NewtonsoftJsonSerializer.cs
Src/Support/Google.Apis.Tests/Json/NewtonsoftJsonSerializerTest.cs

fix: Default JSON serializer instance is not affected by custom global settings for default value handling.

---

Src/Support/Google.Apis.Core/Json/NewtonsoftJsonSerializer.cs

This partially superceeds #2610 and it's a better approach overall as our serializar is not created using the global settings at all, so we don't need to override global settings. Note that JsonConvert.Deserialize uses JsonSerializer.CreateDefault that relies on global settings, and then applies any specific settings. In turn we use JsonSerializer.Create that only applies specific settings. By not using JsonConvert we have stopped being affected by global settings at all. The test from #2610 remains and proves this approach works.
Possibly fixes #2611

fix: Default JSON serializer instance is not affected by any global settings.

---

Src/Support/Google.Apis.Auth.Tests/Google.Apis.Auth.Tests.csproj
Src/Support/Google.Apis.Tests/Apis/Upload/ResumableUploadTest.MultiChunk.cs
Src/Support/Google.Apis.Tests/Google.Apis.Tests.csproj
Src/Support/IntegrationTests/IntegrationTests.csproj

This requires a fix to a test which wasn't awaiting the result of Assert.ThrowsAsync.

chore: Update xunit to 2.6.2

---

Src/Support/Google.Apis/Requests/BatchRequest.cs

By disposing of the batch System.Net.HttpResponseMessage as soon as possible so that it, and more importantly, its contents, may be garbage collected if needed.
This is useful for big response of batch operations, since the whole response is read into memory and then split into individual responses that are then deserialized. Since we keep the whole response string in memory, we don't need to actual response and it's content buffer, which also contains the whole response, may be garbage collected if needed.
Closes #2603

feat: Makes batch response handling more efficient for big responses.

---

.kokoro/autorelease.sh
.kokoro/release-support.sh

dotnet tool restore fails when a package source is missing.

chore: Fix release process

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/Responses/TokenResponseTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/TokenRefreshManagerTests.cs
Src/Support/Google.Apis.Auth/OAuth2/AuthorizationCodeInstalledApp.cs
Src/Support/Google.Apis.Auth/OAuth2/Responses/TokenResponse.cs
Src/Support/Google.Apis.Auth/OAuth2/TokenRefreshManager.cs
Src/Support/Google.Apis.Auth/OAuth2/Web/AuthorizationCodeWebApp.cs

And some code cleanup and refactor.
@jskeet as always, one commit at a time.

fix: Tune auth token refresh and valid windows.

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/GoogleCredentialTests.cs
Src/Support/Google.Apis.Auth/OAuth2/GoogleAuthConsts.cs
Src/Support/Google.Apis.Auth/OAuth2/GoogleCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/HttpRequestMessageExtensions.cs
Src/Support/Google.Apis.Core/Http/ConfigurableMessageHandler.cs
Src/Support/Google.Apis.Core/Http/HttpClientFactory.cs
Src/Support/Google.Apis.Core/Http/HttpClientFromMessageHandlerFactory.cs
Src/Support/Google.Apis.Core/Http/HttpExtenstions.cs
Src/Support/Google.Apis.Core/Http/IHttpClientFactory.cs
Src/Support/Google.Apis.Core/Http/InterceptorDelegatingHandler.cs
Src/Support/Google.Apis.Core/Http/StreamInterceptionHandler.cs
Src/Support/Google.Apis.Core/Util/HttpRequestMessageExtensions.cs
Src/Support/Google.Apis.Tests/Apis/Http/ConfigurableMessageHandlerTest.cs
Src/Support/Google.Apis.Tests/Apis/Services/BaseClientServiceTest.cs
Src/Support/Google.Apis.Tests/Mocks/MockClientService.cs
Src/Support/Google.Apis/Download/MediaDownloader.cs
Src/Support/Google.Apis/Requests/ClientServiceRequest.cs
Src/Support/Google.Apis/Services/BaseClientService.cs
Src/Support/Google.Apis/Upload/ResumableUpload.cs
Src/Support/Google.Apis/Util/HttpRequestMessageExtensions.cs

@jskeet as always, one commit at a time. And I've left a note for you to flag the method we are using from generated code.

feat: Support universe domain for Discovery based libraries

---

Src/Support/Google.Apis.Tests/Apis/Requests/ClientServiceRequestTest.cs
Src/Support/Google.Apis/Requests/ClientServiceRequest.cs

(This will only have any effect when subclasses are created which return a non-null API version.)

feat: support x-goog-api-version header via a new request property

---

Src/Support/Google.Apis.Core/Util/Store/IDataStore.cs

The documentation now reflects the usage of IDataStore by Google.Apis library.
Closes #2704

docs: Be more specific about IDataStore serialization mechanism.

---

CSharpGeneratorFunctions.sh

On my Google Windows box, this speeds up `BuildGenerate.sh --onlygenerate --forcegenerateall` from 31 minutes to 21 minutes. On my Google Linux box, this speeds up the same command from 15 minutes to 11 minutes.

chore: Speed up generator invocation by avoiding "dotnet run"

---

Src/Support/Google.Apis.Tests/Apis/Utils/DiscoveryFormatTest.cs

These "non-round-trip" tests actually *do* round-trip, and are included in RoundTripNonUtc.
Fixes b/318670568

tests: Remove duplicate tests

---

Src/Support/Google.Apis.Auth/OAuth2/ComputeCredential.cs

- Avoid having the same string literal twice
- Use the simpler File.OpenText instead of constructing a StreamReader explicitly
- Use a `using` declaration to simplify the rest of the code
Fixes b/335638570

refactor: Minor improvements to IsLinuxGoogleBiosAsync

---

.kokoro/autorelease.sh

This is failing for the same reasons as Integration V1Alpha was failing before. It's alreayd beeing looked at internally.

chore: Skip generation of Integrations V1.

---

Src/Support/Google.Apis.Auth.AspNetCore3/Google.Apis.Auth.AspNetCore3.csproj

BREAKING CHANGE: Projects using that transitively depend on Microsoft.AspNetCore.Authorization may be broken. They only need to add an implicit dependency themselves. Although this is a breaking change, we will release it a new minor version oly as we find it would be more disruptive otherwise.

build!: Remove unused dependency Microsoft.AspNetCore.Authorization

---

Src/Support/Google.Apis.Auth.Tests/Google.Apis.Auth.Tests.csproj
Src/Support/Google.Apis.Auth.Tests/OAuth2/Pkcs8Tests.cs

Tests now pass in .NET 6 as well.
Closes b/342060412

tests: Update BouncyCastle dependency.

---

Src/Support/Google.Apis.Core/Util/HttpTimeoutInitializer.cs
Src/Support/Google.Apis.Tests/Apis/Services/BaseClientServiceTest.cs
Src/Support/Google.Apis/Services/BaseClientService.cs

feat: Simplify setting the HttpClient timeout

---

.config/dotnet-tools.json

I've generated the support library documentation with this, and it looks fine.

chore: Update docfx to 2.76.0

---

.config/dotnet-tools.json

Generation works locally, but is failing in Kokoro.
See b/342517197

chore: Downgrade docfx to 2.75.3 temporarily

---

BuildGenerated.sh

Note: we still don't get a deterministic build, but this is a step in the right direction.

chore: Fix SourceLink in the build

---

DiscoveryJson/admin_directory_v1.json
DiscoveryJson/admin_directory_v1.json.original
Src/Tools/DiscoveryDocUpdater/Program.cs
Src/Tools/Tools.sln

We only generate from the patched discoveries.
Fixes #2769 .

fix: Do not generate libraries from original discoveries that have been patched.

---

BuildGenerated.sh
BuildSupport.sh
Src/Directory.Build.props
Src/Directory.Build.targets
Src/Support/Google.Apis.Auth.AspNetCore3/Google.Apis.Auth.AspNetCore3.csproj
Src/Support/Google.Apis.Auth.Tests/Google.Apis.Auth.Tests.csproj
Src/Support/Google.Apis.Auth/Google.Apis.Auth.csproj
Src/Support/Google.Apis.Core/Google.Apis.Core.csproj
Src/Support/Google.Apis.IntegrationTests/Google.Apis.IntegrationTests.csproj
Src/Support/Google.Apis.Tests/Google.Apis.Tests.csproj
Src/Support/Google.Apis/Google.Apis.csproj

- Use deterministic builds
- Use a newer version of SourceLink (and centralize it)
- Fix issues with unexpected output files
- Use a newer version of refernece assemblies (and centralize it)
This will generate warnings for Src/Generated projects until we adopt a new version of the generator which doesn't include the reference assemblies and SourceLink package directly.

feat: Improve SourceLink for NuGet packages

---

.kokoro/autorelease.sh

Arguably with this in place we don't *need* the previous changes to GenerateApis.sh and BuildGenerated.sh, but they're probably still worth having. This is an earlier "out" though, and avoids worrying about git etc. (If there's nothing to generate, there are no changes to push.)

tools: Finish the build immediately if we don't have anything to build

---

.kokoro/autogenerate.bat
.kokoro/autogenerate.sh
.kokoro/autorelease.sh
Src/Tools/BuildGeneratedArgumentTranslator/Program.cs
Src/Tools/PackageChecker/PackageChecker.csproj
Src/Tools/PackageChecker/Program.cs
Src/Tools/Tools.sln

The autogenerate script is responsible for updating Discovery docs and source code (and checking the code builds) and pushing a PR to GitHub; the autorelease script finds packages which haven't been released and builds/releases them (without doing any generation etc).
Part of b/350910134 - but we need Kokoro config changes to be submitted at "about the same time"

tools: Separate generation from release

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/ImpersonatedCredentialTests.cs
Src/Support/Google.Apis.Auth/OAuth2/Requests/RequestExtensions.cs
Src/Support/Google.Apis/Responses/HttpResponseMessageExtensions.cs

BREAKING CHANGE: The ComputeCredential and ImpersonatedCredential SignBlobAsync methods will throw a GoogleApiException instead of a HttpRequestExtension. The GoogleApiException makes the HttpResponseMessage content available, which usually includes details about the error.

feat!: Improve error handling when signing with the IAM service

---

.kokoro/autogenerate.sh

After merging this, we can manually run the job to make sure we see the failure.

tools: Make autogenerate.sh fail noisily if we can't create a PR

---

.kokoro/autogenerate.sh

(The version of curl we currently use doesn't support fail-with-body)

chore: Just use --fail instead of --fail-with-body

---

Src/Support/Google.Apis.Auth/Google.Apis.Auth.csproj

The lib/net462 folder in System.Management version 7.0.2 is empty, so this *should* be equivalent.
Addresses #2820.

chore: Use a vanilla reference in net462 for System.Management

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/DefaultCredentialProviderTests.cs

We cannot mock the Compute residency check.
@jskeet this will make the google-api-dotnet-client unit tests green in Kokoro.

tests: Remove tests that are not unit tests.

---

Src/Support/Google.Apis.Auth/OAuth2/GoogleAuthConsts.cs

Environments will support both endpoints for the foreseeable future.
Closes b/339453829

fix: Use `universe-domain` instead of `universe_domain` as the MDS endpoint

---

Src/Support/Google.Apis/Services/BaseClientService.cs

This was exposed by accident and never had any effect.
Closes b/339887021

fix: BaseClientService.UniverDomain setter is obsolete.

---

Src/Support/Google.Apis.Auth.Tests/GoogleAuthConstsTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/ComputeCredentialTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/Flows/AuthorizationCodeFlowTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/ImpersonatedCredentialTests.cs
Src/Support/Google.Apis.Auth.Tests/OAuth2/ServiceAccountCredentialTests.cs
Src/Support/Google.Apis.Auth/OAuth2/ComputeCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/Flows/AuthorizationCodeFlow.cs
Src/Support/Google.Apis.Auth/OAuth2/Flows/GoogleAuthorizationCodeFlow.cs
Src/Support/Google.Apis.Auth/OAuth2/GoogleAuthConsts.cs
Src/Support/Google.Apis.Auth/OAuth2/ImpersonatedCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/ServiceAccountCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/ServiceCredential.cs
Src/Support/Google.Apis.Core/Http/ExponentialBackOffInitializer.cs
Src/Support/Google.Apis.Core/Util/ExponentialBackOff.cs
Src/Support/Google.Apis.Tests/Apis/Http/ExponentialBackOffInitializerTest.cs
Src/Support/Google.Apis.Tests/Apis/Utils/ExponentialBackOffTest.cs
Src/Support/Google.Apis.Tests/Mocks/MockHttpClientFactory.cs
Src/Support/Google.Apis/Services/BaseClientService.cs

Closes b/332955964 and b/368412308
@jskeet , as always, one commit at a time.

feat: Use recommended retries for token and IAM sign blob endpoints.

---

DiscoveryJson/adsense.v2.json
DiscoveryJson/adsenseplatform.v1alpha.json
DiscoveryJson/androidmanagement.v1.json
DiscoveryJson/osconfig.v1.json
DiscoveryJson/osconfig.v1beta.json
Src/Generated/Google.Apis.AdSensePlatform.v1alpha/Google.Apis.AdSensePlatform.v1alpha.cs
Src/Generated/Google.Apis.AdSensePlatform.v1alpha/Google.Apis.AdSensePlatform.v1alpha.csproj
Src/Generated/Google.Apis.Adsense.v2/Google.Apis.Adsense.v2.cs
Src/Generated/Google.Apis.Adsense.v2/Google.Apis.Adsense.v2.csproj
Src/Generated/Google.Apis.AndroidManagement.v1/Google.Apis.AndroidManagement.v1.cs
Src/Generated/Google.Apis.AndroidManagement.v1/Google.Apis.AndroidManagement.v1.csproj
Src/Generated/Google.Apis.OSConfig.v1/Google.Apis.OSConfig.v1.cs
Src/Generated/Google.Apis.OSConfig.v1/Google.Apis.OSConfig.v1.csproj
Src/Generated/Google.Apis.OSConfig.v1beta/Google.Apis.OSConfig.v1beta.cs
Src/Generated/Google.Apis.OSConfig.v1beta/Google.Apis.OSConfig.v1beta.csproj

feat: API regeneration: release-2024-12-04.01-03-39

---

Src/Support/Google.Apis/Services/BaseClientService.cs

feat: Support GOOGLE_CLOUD_UNIVERSE_DOMAIN environment variable.

---

Src/Support/Google.Apis.Auth/OAuth2/GoogleCredential.cs

docs: Add warning note about user provided credential configurations.

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/ServiceAccountCredentialTests.cs
Src/Support/Google.Apis.Auth/OAuth2/ImpersonatedCredential.cs
Src/Support/Google.Apis.Auth/OAuth2/Requests/IamAccessTokenRequest.cs
Src/Support/Google.Apis.Auth/OAuth2/Requests/IamOIdCTokenRequest.cs
Src/Support/Google.Apis.Auth/OAuth2/Requests/IamRequest.cs
Src/Support/Google.Apis.Auth/OAuth2/Requests/IamSignBlobRequest.cs
Src/Support/Google.Apis.Auth/OAuth2/ServiceAccountCredential.cs

feat: Support ID token for SAs in other than the default universe domain

---

ExcludedServices.json

We have b/415809720 for looking into the failure.

build: Skip Compute alpha generation as it's failing

---

ExcludedServices.json

See b/415809720
It's the same failure for alpha and beta. I've tested locally and everything else generates and builds fine.

build: Skip regeneration of Compute beta.

---

Src/Support/Google.Apis.Auth.Tests/OAuth2/ServiceAccountCredentialTests.cs
Src/Support/Google.Apis.Auth/OAuth2/ServiceAccountCredential.cs

When using the .NET client library with a private PSC OAuth2 endpoint for service account authentication, the library produces an "Invalid JWT: Failed audience check" error. This is because the aud claim in the JWT is set to the private token_uri, but Google's infrastructure expects it to be https://oauth2.googleapis.com/token.
This PR modifies ServiceAccountCredential to always use https://oauth2.googleapis.com/token as the audience when creating a JWT to be exchanged for an access token. This aligns the .NET library's behavior with other Google Cloud auth libraries (e.g., Java) and allows service account authentication against private token endpoints.
A new unit test has been added to verify that the JWT aud claim is correctly set to https://oauth2.googleapis.com/token even when a …

fix(auth): Correct JWT audience for Service Account token requests
