googleapis/google-api-dotnet-client

Src/GoogleApis.Tests/Apis/Requests/BatchRequestTest.cs, Src/GoogleApis/Apis/Requests/BatchRequest.cs
Handle multiple HTTP headers in batch responses and update the tests.
=> Fix for issue #548.

Src/GoogleApis.Auth.DotNet4/OAuth2/GoogleCredential.cs, Src/GoogleApis.Auth.DotNet4/OAuth2/ServiceAccountCredential.cs, Src/GoogleApis.Auth.Mvc4/GoogleApis.Auth.Mvc4.csproj, Src/GoogleApis.Auth.Mvc4/OAuth2/Mvc/AuthorizationCodeMvcApp.cs, Src/GoogleApis.Auth.Mvc4/OAuth2/Mvc/FlowMetadata.cs, Src/GoogleApis.Auth.Tests/OAuth2/Flows/AuthorizationCodeFlowTests.cs, Src/GoogleApis.Auth.WP/OAuth2/WebAuthenticationBrokerUserControl.xaml.cs, Src/GoogleApis.Auth.WP/app.config, Src/GoogleApis.Auth.WP81/OAuth2/AuthorizationCodeBroker.cs, Src/GoogleApis.Auth.WP81/app.config, Src/GoogleApis.Auth.Windows/app.config, Src/GoogleApis.Auth/OAuth2/ComputeCredential.cs, Src/GoogleApis.Auth/OAuth2/JsonCredentialParameters.cs, Src/GoogleApis.Auth/OAuth2/ServiceCredential.cs, Src/GoogleApis.Tests/Apis/Services/BaseClientServiceTest.cs, Src/GoogleApis.WP/app.config, Src/GoogleApis.WP81/app.config
After these changes, the Debug and Release builds are clean except for [CS1591](https://msdn.microsoft.com/en-us/library/zk18c1w9.aspx)
=> Fix build warnings

README.md
=> Include Travis build status badge in README.md

Src/Support/GoogleApis/Apis/[Media]/MediaApiErrorHandling.cs
(I spotted the typo when reviewing a previous change...)
=> Fix typo and improve comment for MediaApiErrorHandling

Src/Support/GoogleApis.Auth.DotNet4/OAuth2/GoogleWebAuthorizationBroker.cs
Add an optional parameter for installed applications to provide their
own implementation of ICodeReceiver, while still keeping the current
behavior as a default.
This was allow installed client applications to provide, for example, a code receiver with an embedded web browser.
=> Allow client to provide ICodeReceiver implementation

GeneratedLibraries.proj
Change in apis-client-generator:
https://github.com/mmdriley/apis-client-generator/commit/c1f5340257966671ea6c380ec6a98aee2e510b96
=> Update GeneratedLibraries.proj and ClientGenerator

Src/Support/CommonAssemblyInfo.cs
Need to bring in the fix for #707 and rebuild generated libraries to link against these.
=> Release v1.11.1 of the support libraries

Src/Support/GoogleApis.Tests/Apis/Download/MediaDownloaderTest.cs
Wasn't anticipating a problem, but realized we didn't have any coverage for this.
=> Add a MediaDownloader test with an empty response body

GeneratedLibraries.proj
Perform nuget restore for all NetStandard projects before build.
#695
=> Fix NetStandard build

Src/Support/GoogleApis/Apis/[Media]/Download/MediaDownloader.cs
=> Fix MediaDownload overflow bug

NuGet.Config, Src/Support/GoogleApis.Core/Apis/Util/Utilities.cs, SupportLibraries.proj
Add NuGet.Config.
Use local package repository for all builds.
Tidy SupportLibraries.proj; and add "Clean" target
Fix XML comment.
=> Improve build

GeneratedLibraries.proj, SupportLibraries.proj
Fix nuget restore for netstandard1.3, and improve .proj files
=> Tidy up NetStandard1.3 build gened libs

Src/Support/GoogleApis.Auth.NetStandard/project.json, Src/Support/GoogleApis.Auth/Google.Apis.Auth.nuspec, Src/Support/GoogleApis.Core/Google.Apis.Core.nuspec, Src/Support/GoogleApis/Google.Apis.nuspec
Replace NetStandard.Library deps with explicit dependency list
=> Fix support library dependecies

Src/Support/GoogleApis.Auth.DotNet4.Tests/OAuth2/ServiceAccountCredentialTests.cs, Src/Support/GoogleApis.Auth.PlatformServices_Shared/OAuth2/ServiceAccountCredential.cs
=> Support X509 certificates in netstandard

Src/Support/GoogleApis.Auth/Google.Apis.Auth.nuspec
=> Add missing dependency in .NET45 to Google.Apis

ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/___package_name___/NetStandard/___package_name___.csproj.tmpl
=> Strongly name netstandard generated libraries

ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/_method_resumable.tmpl
=> Fix formatting of xmldoc for resumable methods

.gitignore, GeneratedLibraries.proj, Src/Tools/DiscoveryDocPatcher/App.config, Src/Tools/DiscoveryDocPatcher/DiscoveryDocPatcher.csproj, Src/Tools/DiscoveryDocPatcher/DiscoveryDocPatcher.sln, Src/Tools/DiscoveryDocPatcher/Patcher.cs, Src/Tools/DiscoveryDocPatcher/Program.cs, Src/Tools/DiscoveryDocPatcher/Properties/AssemblyInfo.cs, Src/Tools/DiscoveryDocPatcher/packages.config
=> Patch directory and games discovery-docs

Src/Support/GoogleApis.Core/Apis/Json/JsonExplicitNull.cs, Src/Support/GoogleApis.Core/Apis/Json/JsonExplicitNullAttribute.cs, Src/Support/GoogleApis.Core/Apis/Json/NewtonsoftJsonSerializer.cs, Src/Support/GoogleApis.Core/GoogleApis.Core_Shared.projitems, Src/Support/GoogleApis.Tests/GoogleApis.Tests.csproj, Src/Support/GoogleApis.Tests/Json/JsonExplicitNullTest.cs, run_tests_dotnetcore.sh, travis.sh
=> Allow null values to be present in JSON

Src/Support/GoogleApis/Apis/[Media]/Download/MediaDownloader.cs
(This enables hash validation in subclasses.)
No tests as they'd be more longwinded than the code itself, by a considerable margin.
=> Add protected virtual methods to MediaDownloader for closer response inspection

Src/Support/GoogleApis.Auth.WP81/OAuth2/GoogleWebAuthorizationBroker.cs
=> Make AuthorizeAsync(ClientSecrets...) public

Src/Support/GoogleApis.Auth.PlatformServices_Shared/OAuth2/ServiceAccountCredential.cs, Src/Support/GoogleApis.Auth/OAuth2/Flows/GoogleAuthorizationCodeFlow.cs, Src/Support/GoogleApis.Auth/OAuth2/GoogleAuthConsts.cs, Src/Support/GoogleApis.Tests/Apis/Utils/NullDataStoreTest.cs, Src/Support/GoogleApis/Apis/Util/Store/NullDataStore.cs, Src/Support/IntegrationTests_Net45/AuthClientSecretsTests.cs, Src/Support/IntegrationTests_Net45/AuthUriConstsTests.cs, Src/Support/IntegrationTests_Net45/IntegrationTests_Net45.csproj, Src/Support/IntegrationTests_NetCore/ServiceAccountTests.cs
Add integration test for oauth2 authentication.
Fix bugs in NullDataStore
=> Add new OpenID Connect auth endpoints

Src/Support/GoogleApis.Auth.Tests/OAuth2/Responses/TokenResponseTests.cs, Src/Support/GoogleApis.Auth/OAuth2/Responses/TokenResponse.cs
=> Extend refresh token window from 1 minute to 5 minutes

Src/Support/GoogleApis.Auth.DotNet4/OAuth2/LocalServerCodeReceiver.cs
Log error, and provide a more helpful exception message
Updates #907
=> Better handle errors with browser launch

Src/Support/GoogleApis/Apis/Requests/ClientServiceRequest.cs
=> Only add apikey request parameter if not null

NuGet.Config
=> Update nuget config

Src/Support/GoogleApis.Auth.PlatformServices_Shared/OAuth2/LocalServerCodeReceiver.cs, Src/Support/IntegrationTests_Net45/GoogleWebAuthorizationBrokerTests.cs, Src/Support/IntegrationTests_Net45/IntegrationTests_Net45.csproj
=> Honour cancellation in GoogleWebAuthorizationBroker.AuthorizeAsync()

Src/Support/Google.Apis.Auth.Mvc/Google.Apis.Auth.Mvc.csproj, Src/Support/Google.Apis.Auth.Mvc/OAuth2/Mvc/AuthorizationCodeMvcApp.cs, Src/Support/Google.Apis.Auth.Mvc/OAuth2/Mvc/Controllers/AuthCallbackController.cs, Src/Support/Google.Apis.Auth.Mvc/OAuth2/Mvc/Filters/AuthActionFilter.cs, Src/Support/Google.Apis.Auth.Mvc/OAuth2/Mvc/FlowMetadata.cs, Src/Support/Google.Apis.Auth/Google.Apis.Auth.csproj, Src/Support/Google.Apis.Core/Google.Apis.Core.csproj, Src/Support/Google.Apis/Google.Apis.csproj, Src/Support/GoogleApisClient.sln
Adds Auth.Mvc for net45 only. Will address net core later.
Also fix VS2017 project loading issue
=> Add Auth.Mvc project

Src/Support/Google.Apis.Auth/OAuth2/Flows/AuthorizationCodeFlow.cs, Src/Support/Google.Apis.Auth/OAuth2/Flows/GoogleAuthorizationCodeFlow.cs, Src/Support/Google.Apis.Auth/OAuth2/Requests/TokenRequestExtenstions.cs, Src/Support/Google.Apis.Auth/OAuth2/Responses/TokenResponse.cs, Src/Support/Google.Apis.Auth/OAuth2/Responses/TokenResponseException.cs
=> Only delete RefershToken on client error (not server error)

Src/Support/Google.Apis.Auth/OAuth2/LocalServerCodeReceiver.cs
=> Use loopback address, not localhost

Src/Support/Google.Apis.Auth/OAuth2/GoogleCredential.cs
=> Provide synchronous access to default credentials

ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/_method.tmpl
=> Support range downloads in generated code

Src/Support/Google.Apis.Core/Discovery/Parameter.cs, Src/Support/Google.Apis.Core/GoogleApiException.cs, Src/Support/Google.Apis.Core/Http/BackOffHandler.cs, Src/Support/Google.Apis.Core/Http/ExponentialBackOffInitializer.cs, Src/Support/Google.Apis.Core/Http/HttpClientFactory.cs, Src/Support/Google.Apis.Core/Http/HttpConsts.cs, Src/Support/Google.Apis.Core/Http/MaxUrlLengthInterceptor.cs, Src/Support/Google.Apis.Core/Json/NewtonsoftJsonSerializer.cs, Src/Support/Google.Apis.Core/Logging/NullLogger.cs, Src/Support/Google.Apis.Core/Requests/RequestError.cs, Src/Support/Google.Apis.Core/Requests/SingleError.cs, Src/Support/Google.Apis.Core/Util/ExponentialBackOff.cs, Src/Support/Google.Apis.Core/Util/IClock.cs, Src/Support/Google.Apis.Core/Util/Repeatable.cs, Src/Support/Google.Apis.Core/Util/UriPatcher.cs
Now builds with no warnings. Updates #1029
=> Add XmlDoc to Google.Apis.Core

Src/Support/Google.Apis.Auth.Mvc/OAuth2/Mvc/Controllers/AuthCallbackController.cs, Src/Support/Google.Apis.Auth/OAuth2/AuthorizationCodeInstalledApp.cs, Src/Support/Google.Apis.Auth/OAuth2/BearerToken.cs, Src/Support/Google.Apis.Auth/OAuth2/ComputeCredential.cs, Src/Support/Google.Apis.Auth/OAuth2/Flows/AuthorizationCodeFlow.cs, Src/Support/Google.Apis.Auth/OAuth2/Flows/GoogleAuthorizationCodeFlow.cs, Src/Support/Google.Apis.Auth/OAuth2/PromptCodeReceiver.cs, Src/Support/Google.Apis.Auth/OAuth2/Responses/TokenErrorResponse.cs, Src/Support/Google.Apis.Auth/OAuth2/ServiceCredential.cs, Src/Support/Google.Apis.Auth/OAuth2/UserCredential.cs, Src/Support/Google.Apis/Download/MediaDownloader.cs, Src/Support/Google.Apis/Requests/ClientServiceRequest.cs, Src/Support/Google.Apis/Services/BaseClientService.cs, Src/Support/Google.Apis/Util/Store/FileDataStore.cs
=> Add all remaining XmlDoc to support libraries

get_discovery_documents.py
=> Ignore discovery-doc download errors

FAQ.md, README.md
This is exactly the same maintenance notice in the readme as in #1048, but also includes a FAQ with a few more details.
=> Add maintenance notice, and FAQ

Src/Support/Google.Apis.Auth/OAuth2/GoogleCredential.cs
=> Allow User to be set in a service credential

Src/Support/Google.Apis.Auth/OAuth2/LocalServerCodeReceiver.cs
=> Try both 127.0.0.1 and localhost in the local code receiver

FAQ.md, Src/Support/Google.Apis.Auth/OAuth2/GoogleWebAuthorizationBroker.cs
=> Extra documentation for GoogleWebAuthorizationBroker

ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/___package_name___/___package_name___.csproj.tmpl
=> Update nuget package project site

Src/Support/Google.Apis.Auth.Tests/GoogleJsonWebSignatureTests.cs, Src/Support/Google.Apis.Auth/GoogleJsonWebSignature.cs
=> Additional JWT claims; full JWT verification

Src/Support/Google.Apis.Auth.Tests/OAuth2/LimitedLocalhostHttpServerTests.cs, Src/Support/Google.Apis.Auth/OAuth2/AuthorizationCodeInstalledApp.cs, Src/Support/Google.Apis.Auth/OAuth2/LocalServerCodeReceiver.cs, appveyor.yml
Fixes #540. Really fixes #1055
=> Test for best callback URI; fix hanging browsers

Src/Support/Google.Apis.Auth.Tests/OAuth2/GoogleCredentialTests.cs, Src/Support/Google.Apis.Auth/OAuth2/GoogleCredential.cs
=> Implement an AccessToken credential

Src/Support/Google.Apis.Tests/Apis/Services/BaseClientServiceTest.cs, Src/Support/Google.Apis/Services/BaseClientService.cs
=> Validate ApplicationName

ClientGenerator/src/googleapis/codegen/languages/csharp/default/features.json, Src/Support/CommonProjectProperties.xml
Also change nupkg project URL to github page, per #655
=> Update version v1.27.1 -> v1.28.0

Src/Support/Google.Apis.Auth/OAuth2/LocalServerCodeReceiver.cs, Src/Support/IntegrationTests/GoogleWebAuthorizationBrokerTests.cs
=> Pass auth URL correctly to browser

Src/Support/Google.Apis.Core/Http/Delegates.cs, Src/Support/Google.Apis.Tests/Apis/Upload/ResumableUploadTest.cs, Src/Support/Google.Apis/Upload/ResumableUpload.cs
I haven't written tests yet, although the existing tests pass.
(Separately, we might want to start using async stream reading, but that's a different matter.)
=> Support upload data interception

Src/Support/Google.Apis.Tests/Apis/Requests/ClientServiceRequestTest.cs, Src/Support/Google.Apis/Services/BaseClientService.cs
=> Correctly handle non-JSON error responses

Src/Support/Google.Apis.Tests/Apis/Upload/ResumableUploadTest.cs, Src/Support/Google.Apis/Upload/ResumableUpload.cs
=> Treat range header name as case insensitive

FAQ.md, README.md
=> Add docs about client re-use

FAQ.md, HowToGenerateAPackage.md
=> Doc how to generate a nuget package

Src/Support/Google.Apis.Auth/OAuth2/ComputeCredential.cs
This matches (roughly) the Java implementation, and observationally
appears to be more reliable than a single request with a long timeout.
=> Apply a retry policy for detecting GCE

Src/Support/Google.Apis.Auth.Tests/OAuth2/Requests/GoogleAuthorizationCodeRequestUrlTests.cs, Src/Support/Google.Apis.Auth/OAuth2/Requests/GoogleAuthorizationCodeRequestUrl.cs
=> Add 'Prompt' property for auth URL

Src/Support/Google.Apis.Core/Http/ConfigurableMessageHandler.cs
=> Dispose of responses in all non-success cases

Src/Support/Google.Apis.Auth/GoogleJsonWebSignature.cs, Src/Support/Google.Apis.Auth/OAuth2/ComputeCredential.cs, Src/Support/Google.Apis.Auth/OAuth2/Flows/GoogleAuthorizationCodeFlow.cs, Src/Support/Google.Apis.Core/Http/ConfigurableMessageHandler.cs
=> Add ConfigureAwait(false) where missing

BuildGenerated.sh, BuildSupport.sh, ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/___package_name___/___package_name___.csproj.tmpl, Src/Support/CommonProjectProperties.xml, Src/Support/Google.Apis.Auth.Mvc/Google.Apis.Auth.Mvc.csproj, Src/Support/Google.Apis.Auth/Google.Apis.Auth.csproj, Src/Support/Google.Apis.Core/Google.Apis.Core.csproj, Src/Support/Google.Apis/Google.Apis.csproj
Verified locally that support and generated packages contain sourcelink information
=> Add sourcelink to support and generated packages

Src/Support/Google.Apis.Tests/Apis/Requests/ClientServiceRequestTest.cs, Src/Support/Google.Apis.Tests/Apis/Requests/RequestBuilderTest.cs, Src/Support/Google.Apis/Download/MediaDownloader.cs, Src/Support/Google.Apis/Requests/ClientServiceRequest.cs, Src/Support/IntegrationTests/StorageApiTests.cs
=> Correct URI escaping

Src/Support/Google.Apis.Auth.Tests/GoogleJsonWebSignatureTests.cs, Src/Support/Google.Apis.Auth/GoogleJsonWebSignature.cs
=> Allow for local clock skew in JWT validation

Src/Support/Google.Apis.Auth.Tests/OAuth2/GoogleCredentialTests.cs, Src/Support/Google.Apis.Auth/OAuth2/DefaultCredentialProvider.cs, Src/Support/Google.Apis.Auth/OAuth2/Flows/GoogleAuthorizationCodeFlow.cs, Src/Support/Google.Apis.Auth/OAuth2/JsonCredentialParameters.cs, Src/Support/Google.Apis.Auth/OAuth2/ServiceAccountCredential.cs
=> Load and expose project ID in user and service credentials

Src/Support/Google.Apis.Auth/Google.Apis.Auth.csproj, Src/Support/Google.Apis.Core/Google.Apis.Core.csproj, Src/Support/Google.Apis/Google.Apis.csproj
Changes to support the full framework version of System.Net.Http when building in the full framework.
=> Full system net http

ClientGenerator/src/googleapis/codegen/languages/csharp/default/features.json, Src/Support/CommonProjectProperties.xml
Unless you're aware of anything else that should go in this version...
=> Update version v1.34.0 -> v1.35.0

Src/Support/Google.Apis.Auth.PlatformServices/Google.Apis.Auth.PlatformServices.csproj, Src/Support/Google.Apis.Auth.Tests/Google.Apis.Auth.Tests.csproj, Src/Support/Google.Apis.Auth.Tests/OAuth2/Pkcs8Tests.cs, Src/Support/Google.Apis.Auth.Tests/OAuth2/ServiceAccountCredentialTests.cs, Src/Support/Google.Apis.Auth/Google.Apis.Auth.csproj, Src/Support/Google.Apis.Auth/GoogleJsonWebSignature.cs, Src/Support/Google.Apis.Auth/OAuth2/LocalServerCodeReceiver.cs, Src/Support/Google.Apis.Auth/OAuth2/PromptCodeReceiver.cs, Src/Support/Google.Apis.Auth/OAuth2/ServiceAccountCredential.cs, Src/Support/Google.Apis.Core/Google.Apis.Core.csproj, Src/Support/Google.Apis.Tests/Apis/Upload/ResumableUploadTest.cs, Src/Support/Google.Apis.Tests/Google.Apis.Tests.csproj, Src/Support/Google.Apis.Tests/System.Net/AsyncStream.cs, Src/Support/Google.Apis.Tests/System.Net/Extensions.cs, Src/Support/Google.Apis.Tests/System.Net/HttpListener.cs, Src/Support/Google.Apis.Tests/System.Net/HttpListenerContext.cs, Src/Support/Google.Apis.Tests/System.Net/HttpListenerException.cs, Src/Support/Google.Apis.Tests/System.Net/HttpListenerRequest.cs, Src/Support/Google.Apis.Tests/System.Net/HttpListenerResponse.cs, Src/Support/Google.Apis/Google.Apis.csproj
Updates #1245
Integration tests and generated packages to follow.
=> Target netstandard2.0 in support packages and tests

Src/Support/IntegrationTests/IntegrationTests.csproj, Src/Support/IntegrationTests/ServiceAccountTests.cs
=> Update integration tests to include netcoreapp2.0

Src/Support/Google.Apis.Auth/OAuth2/GoogleAuthConsts.cs
=> Update auth URLs

Src/Support/Google.Apis.Auth/OAuth2/Flows/GoogleAuthorizationCodeFlow.cs, Src/Support/IntegrationTests/IntegrationTests.csproj, Src/Support/IntegrationTests/RevocationTests.cs, Src/Support/IntegrationTests/RevokationTests.cs
=> Revoke using POST, not GET

Src/Support/Google.Apis.Auth.Tests/OAuth2/Flows/GoogleAuthorizationCodeFlowTests.cs, Src/Support/Google.Apis.Auth/OAuth2/Flows/GoogleAuthorizationCodeFlow.cs
=> Allow prompt use in authorization flow

FAQ.md
=> Update FAQ with the more flexible GoogleApiHttpBody workaround

Src/Support/Google.Apis.Auth/OAuth2/RequestExtensions.cs
=> Improve comment on AddCredential() extension method

Src/Support/Google.Apis.Auth.Tests/OAuth2/LimitedLocalhostHttpServerTests.cs, Src/Support/Google.Apis.Auth/OAuth2/LocalServerCodeReceiver.cs
=> Respect cancellation during accept operation

ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/___package_name___/___package_name___.cs.tmpl, ClientGenerator/src/googleapis/codegen/testdata/golden/csharp/default/endpoints_google_owned.golden, ClientGenerator/src/googleapis/codegen/testdata/golden/csharp/default/endpoints_third_party.golden, ClientGenerator/src/googleapis/codegen/testdata/golden/csharp/default/kitchen_sink.golden, Src/Support/Google.Apis/Services/BaseClientService.cs
I haven't run the generator at all yet - I'm creating this PR so we
have something to discuss.
=> Configurable BaseUri

ClientGenerator/src/googleapis/codegen/languages/csharp/default/features.json, Src/Support/CommonProjectProperties.xml
=> Update version v1.39.0 -> v1.40.0

.kokoro/BuildAndUploadGeneratedDocs.bat, .kokoro/BuildAndUploadGeneratedDocs.sh, .kokoro/BuildGeneratedDocs.sh, .kokoro/BuildSupportDocs.sh, .kokoro/UploadGeneratedDocs.sh, Docs/docfx-2.json
Currently untested, but I won't merge until I've got "all but the upload itself" working
=> Kokoro scripts to build and upload docs for generated packages

Src/Support/Google.Apis.Core/Http/ConfigurableMessageHandler.cs, Src/Support/Google.Apis.Core/Http/HttpClientFactory.cs, Src/Support/Google.Apis.Core/Http/IHttpClientFactory.cs, Src/Support/Google.Apis.Tests/Apis/Http/ConfigurableMessageHandlerTest.cs, Src/Support/Google.Apis.Tests/Apis/Services/BaseClientServiceTest.cs, Src/Support/Google.Apis/Requests/VersionHeaderBuilder.cs, Src/Support/Google.Apis/Services/BaseClientService.cs, Src/Support/Google.Apis/Upload/ResumableUpload.cs
This will be followed up by GAX and google-cloud-dotnet PRs
=> Support x-goog-api-client in REST libraries

ClientGenerator/src/googleapis/codegen/languages/csharp/default/features.json, Src/Support/CommonProjectProperties.xml
Reverts googleapis/google-api-dotnet-client#1443
=> Revert "Update version v1.40.3 -> v1.41.0"

Src/Support/Google.Apis/Upload/ResumableUpload.cs
Turn _PrepareNextChunkKnownSize_ and _PrepareNextChunkUnknownSize_ into async methods so that _Stream.Read_ calls can be turned into _Stream.ReadAsync_.
Fixes _"Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead"_ in AspNetCore 3.0 projects.
=> Turn sync into async methods

ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/_method_resumable.tmpl, Src/Support/Google.Apis/Upload/ResumableUpload.cs
=> Document stream behaviour for resumable upload

Src/Support/Google.Apis.Core/Http/HttpClientFactory.cs
=> Virtual method to create a HttpClientHander

.kokoro/UploadGeneratedDocs.sh, .kokoro/UploadSupportDocs.sh
(I'm not sure whether this has always been broken or not.)
=> Fix the GitHub link on the docs widget

Src/Support/Google.Apis.Auth.Tests/OAuth2/GoogleCredentialTests.cs, Src/Support/Google.Apis.Auth/OAuth2/DefaultCredentialProvider.cs, Src/Support/Google.Apis.Auth/OAuth2/GoogleCredential.cs, Src/Support/Google.Apis.Auth/TaskExtensions.cs, Src/Support/Google.Apis.Core/Json/NewtonsoftJsonSerializer.cs, Src/Support/Google.Apis.Core/Util/TaskExtensions.cs, Src/Support/Google.Apis.Tests/Apis/Utils/TaskExtensionsTest.cs
This commit currently demonstrates the new production code; tests
will be added once the approach is agreed upon.
=> Allow async and cancellable credential fetching

Src/Support/Google.Apis.Auth.Tests/Google.Apis.Auth.Tests.csproj, Src/Support/Google.Apis.Core/Google.Apis.Core.csproj, Src/Support/Google.Apis.Tests/Google.Apis.Tests.csproj, Src/Support/Google.Apis/Google.Apis.csproj, Src/Support/IntegrationTests/IntegrationTests.csproj
=> Upgrade newtonsoft.json from v10.x -> v12.x

Src/Support/Google.Apis/ETagAction.cs, Src/Support/IntegrationTests/StorageApiTests.cs
GCSs etag If-Match/If-None-Match support is currently broken. Also fix doc error.
=> Skip ETag test

BACKLOG.md
- Closes #1105
- Closes #1414
- Closes #1427
=> Move three issues to the backlog

Src/Support/Google.Apis/Upload/ResumableUpload.cs
These commits should make no observable difference, but refactor the code to isolate the use of "one big byte array" for the data for each chunk.
Once this PR is in place, the UploadBuffer class can be refactored to use multiple 64K arrays instead of a single huge one (that ends up on the large object heap).
(It can even potentially do that lazily, to avoid allocating 10MB for each upload if only a few case is required...)
=> Fiddly refactoring of ResumableUpload to allow for smaller arrays

Src/Support/Google.Apis/Upload/ResumableUpload.cs
This fixes https://github.com/googleapis/google-cloud-dotnet/issues/4212 as well as being much more efficient in general - we only allocate a single buffer per upload, lazily allocating 64K blocks within that buffer. This means that small uploads will only require a 64K allocation (regardless of whether the stream is seekable or not) and seekable streams won't keep on reallocating on every iteration.
While this is being reviewed, I'll locally build a test NuGet package and run the Google.Cloud.Storage.V1 integration tests and snippets as further validation that there are no behavioural changes.
=> Rewrite UploadBuffer to use small blocks

Src/Tools/DiscoveryDocPatcher/Patcher.cs, Src/Tools/DiscoveryDocPatcher/Program.cs
=> Adds field description to Admin Directory patch.

ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/_model.tmpl, Src/Generated/Google.Apis.AdExchangeBuyer.v1_2/Google.Apis.AdExchangeBuyer.v1_2.cs, Src/Generated/Google.Apis.AdExchangeBuyer.v1_3/Google.Apis.AdExchangeBuyer.v1_3.cs, Src/Generated/Google.Apis.AdExchangeBuyer.v1_4/Google.Apis.AdExchangeBuyer.v1_4.cs, Src/Generated/Google.Apis.Admin.DataTransfer.datatransfer_v1/Google.Apis.Admin.DataTransfer.datatransfer_v1.cs, Src/Generated/Google.Apis.Admin.Reports.reports_v1/Google.Apis.Admin.Reports.reports_v1.cs, Src/Generated/Google.Apis.Analytics.v3/Google.Apis.Analytics.v3.cs, Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs, Src/Generated/Google.Apis.Calendar.v3/Google.Apis.Calendar.v3.cs, Src/Generated/Google.Apis.Dfareporting.v3_3/Google.Apis.Dfareporting.v3_3.cs, Src/Generated/Google.Apis.Dfareporting.v3_4/Google.Apis.Dfareporting.v3_4.cs, Src/Generated/Google.Apis.Drive.v2/Google.Apis.Drive.v2.cs, Src/Generated/Google.Apis.Drive.v3/Google.Apis.Drive.v3.cs, Src/Generated/Google.Apis.Plus.v1/Google.Apis.Plus.v1.cs, Src/Generated/Google.Apis.Storage.v1/Google.Apis.Storage.v1.cs, Src/Generated/Google.Apis.Webmasters.v3/Google.Apis.Webmasters.v3.cs
This is purely for the sake of easier generation from C#
=> Change generated code for DateTime handling

ClientGenerator/src/googleapis/codegen/languages/csharp/default/templates/_method.tmpl, Src/Generated/Google.Apis.AdExchangeBuyer.v1_4/Google.Apis.AdExchangeBuyer.v1_4.cs, Src/Generated/Google.Apis.AdSenseHost.v4_1/Google.Apis.AdSenseHost.v4_1.cs, Src/Generated/Google.Apis.Admin.Reports.reports_v1/Google.Apis.Admin.Reports.reports_v1.cs, Src/Generated/Google.Apis.AndroidPublisher.v3/Google.Apis.AndroidPublisher.v3.cs, Src/Generated/Google.Apis.Dfareporting.v3_3/Google.Apis.Dfareporting.v3_3.cs, Src/Generated/Google.Apis.Dfareporting.v3_4/Google.Apis.Dfareporting.v3_4.cs, Src/Generated/Google.Apis.DisplayVideo.v1/Google.Apis.DisplayVideo.v1.cs, Src/Generated/Google.Apis.Games.v1/Google.Apis.Games.v1.cs, Src/Generated/Google.Apis.GamesConfiguration.v1configuration/Google.Apis.GamesConfiguration.v1configuration.cs, Src/Generated/Google.Apis.Reseller.v1/Google.Apis.Reseller.v1.cs, Src/Generated/Google.Apis.ShoppingContent.v2/Google.Apis.ShoppingContent.v2.cs, Src/Generated/Google.Apis.ShoppingContent.v2_1/Google.Apis.ShoppingContent.v2_1.cs, Src/Generated/Google.Apis.Testing.v1/Google.Apis.Testing.v1.cs, Src/Generated/Google.Apis.YouTube.v3/Google.Apis.YouTube.v3.cs
I *hope* this is the last change I need for the Python generator - at least for the C# code.
=> Avoid unnecessary qualification of enum names

Src/Support/Google.Apis.Auth.AspNetCore3.IntegrationTests/README.MD
=> Adds README.md to Google.Apis.Auth.AspNetCore3.IntegrationTests.

.github/workflows/build.yml
(This does what the existing Travis configuration does.)
=> Add GitHub actions support

BACKLOG.md
I've left out #1547, but not sure if we should add it as well. Seems to be a different kind of Auth related concern and probably something that each language could do on their own?
=> chore: Move Auth related issues to backlog

Src/Generated/Google.Apis.Admin.DataTransfer.datatransfer_v1/Google.Apis.Admin.DataTransfer.datatransfer_v1.cs, Src/Generated/Google.Apis.Admin.DataTransfer.datatransfer_v1/Google.Apis.Admin.DataTransfer.datatransfer_v1.csproj, Src/Generated/Google.Apis.Admin.DataTransfer.datatransfer_v1/app.net40.config, Src/Generated/Google.Apis.Admin.DataTransfer.datatransfer_v1/app.netstandard10.config, Src/Generated/Google.Apis.Admin.Reports.reports_v1/Google.Apis.Admin.Reports.reports_v1.cs, Src/Generated/Google.Apis.Admin.Reports.reports_v1/Google.Apis.Admin.Reports.reports_v1.csproj, Src/Generated/Google.Apis.Admin.Reports.reports_v1/app.net40.config, Src/Generated/Google.Apis.Admin.Reports.reports_v1/app.netstandard10.config
(This is the result of "./BuildGenerated.sh --skipdownload")
Fixes #1733
=> Regenerate Admin APIs

BuildGenerated.sh
This is ugly, but appears to work, and should massively reduce the
churn of packages.
=> After downloading Discovery docs, revert revision-only changes

Src/Support/Google.Apis.Core/Requests/RequestError.cs, Src/Support/Google.Apis.Tests/Apis/Download/MediaDownloaderTest.cs, Src/Support/Google.Apis.Tests/Apis/Requests/BatchRequestTest.cs, Src/Support/Google.Apis.Tests/Apis/Services/BaseClientServiceTest.cs, Src/Support/Google.Apis/Media/MediaApiErrorHandling.cs, Src/Support/Google.Apis/Services/BaseClientService.cs
=> feat: Include the full response content on RequestError.

Src/Support/Google.Apis.Core/Http/ConfigurableHttpClient.cs, Src/Support/Google.Apis.Core/Http/HttpClientFromMessageHandlerFactory.cs, Src/Support/Google.Apis.Tests/Apis/Http/HttpClientFromMessageHandlerFactoryTests.cs, Src/Support/IntegrationTests/HttpClientFromMessageHandlerFactoryTests.cs, Src/Support/IntegrationTests/IntegrationTests.csproj
See #1756 for context.
FYI @trejjam
=> Proposal: feat: Allows injecting System.Net.Http.HttpMessageHandler when creating Google.Apis.Http.ConfigurableHttpClient

Src/Support/CommonProjectProperties.xml, features.json
Features:
* #1757 Allows injecting `System.Net.Http.HttpMessageHandler` when creating `Google.Apis.Http.ConfigurableHtppClient`.
* #1749 and #1753 Include more detailed error information in batch operations.
* #1741 Allows parameter validation to be bypassed.
* #1710 Makes obtaining default credentials more async (when possible).
* #1665 Adss support for GCE_METADATA_HOST environment variable.
=> Update version 1.48.0 => 1.49.0

Src/Support/CommonProjectProperties.xml, features.json
Features:
* googleapis/gapic-generator-csharp#313 Makes the request's DownloadRange methods use the MediaDownloader already defined in the request
* #1797 Makes extra parameters available in AuthorizationCodeResponseUrl
=> Update version: 1.50.0 -> 1.51.0

Src/Tools/DiscoveryDocPatcher/Program.cs
And modify some of the expected content according to the new discovery.
In preparation for generating Admin Directory again.
=> chore: Reactivate admin_directory_v1.json patching.

BACKLOG.md
Closes #1827
Closes #1814
Closes #1812
=> chore: Moves some Auth related issue to the backlog.

BACKLOG.md
=> chore: Move Blazor related issue to the backlog.

.kokoro/BuildAndUploadGeneratedDocs.sh, .kokoro/BuildAndUploadSupportDocs.sh, .kokoro/populatesecrets.sh
Accompanying CL will be submited soon...
=> ci: Moves away from Keystore for secret storage.

Src/Support/Google.Apis.Auth.Tests/OAuth2/ServiceAccountCredentialTests.cs, Src/Support/Google.Apis.Auth/OAuth2/AccessTokenCredential.cs, Src/Support/Google.Apis.Auth/OAuth2/ComputeCredential.cs, Src/Support/Google.Apis.Auth/OAuth2/GoogleCredential.cs, Src/Support/Google.Apis.Auth/OAuth2/IGoogleCredential.cs, Src/Support/Google.Apis.Auth/OAuth2/ImpersonatedCredential.cs, Src/Support/Google.Apis.Auth/OAuth2/ServiceAccountCredential.cs, Src/Support/Google.Apis.Auth/OAuth2/UserCredential.cs
This is something that I've wanted to do for a while now. I think it will simplify upcoming implementations.
=> refactor: Simplify the GoogleCredential hierarchy

Src/Support/CommonProjectProperties.xml, features.json
Features
* #1832 Helper for loading Client Secrets directly from file.
* #1838 and #1874 Support for credential impersonation.
* #1851 Make it easier to configure a credential's HTTP client, in particular it's now easier to set a proxy to be used for token fetching.
Fixes
* #1874 ServiceAccountCredential should copy scopes from initializer.
Dependencies
* #1842 System.Net.Http to 4.3.4
* #1873 Add target for .NET 4.6.1
=> Update version: 1.51.0 -> 1.52.0

BACKLOG.md
=> chore: Adds #1857 to the Backlog

Src/Support/Google.Apis.Auth.Tests/JsonWebSignatureTests.cs, Src/Support/Google.Apis.Auth/JsonWebSignature.cs
=> feat: Allows for custom payloads to be specified for JWT token verification.

Src/Support/Google.Apis.Auth.Tests/OAuth2/GoogleCredentialTests.cs, Src/Support/Google.Apis.Auth.Tests/OAuth2/ServiceAccountCredentialTests.cs, Src/Support/Google.Apis.Auth/OAuth2/ServiceAccountCredential.cs, Src/Support/IntegrationTests/IntegrationTests.Utils/Helper.cs, Src/Support/IntegrationTests/ServiceAccountTests.cs
This PR allows self signed jwt to use scopes.
AIP: https://google.aip.dev/auth/4111
=> feat: allow scopes for self signed jwt

Src/Support/CommonProjectProperties.xml, features.json
Features
* #1890 Allows scopes for self signed JWTs
* #1886 Allows custom payloads for JWTs verification
=> Update version: 1.52.0 -> 1.53.0

Src/Support/Google.Apis.Core/Requests/Parameters/ParameterUtils.cs, Src/Support/Google.Apis.Tests/Apis/Requests/Parameters/ParameterUtilsTest.cs
This will allow us to represent repeable enum query fields without any breaking changes.
The test gives an idea of what the generated code would look like: after this change is released, we'd start generating two properties for each repeated enum parameter. (We still need to generate the single one for compatibility reasons.)
=> feat: Handle multiple properties for the same request parameter

Src/Support/CommonProjectProperties.xml, features.json
Features
* #1914 Which add supports for multiple properties for the same parameter. This will allow to add support for repeated enums in query strings.
=> Update version: 1.53.0 -> 1.54.0

.github/renovate.json, Src/Support/Google.Apis.Auth.AspNetCore/Google.Apis.Auth.AspNetCore.csproj
Closes #1939
Closes #1940
Closes #1941
=> ci: Configures renovate for Google.Apis.Auth.AspNetCore

.github/renovate.json, Src/Support/Google.Apis.Auth.AspNetCore.IntegrationTests/Google.Apis.Auth.AspNetCore.IntegrationTests.csproj, Src/Support/Google.Apis.Auth.Mvc/Google.Apis.Auth.Mvc.csproj, Src/Support/Google.Apis.Auth.Tests/Google.Apis.Auth.Tests.csproj, Src/Support/Google.Apis.Auth.Tests/JsonWebSignatureTests.cs, Src/Support/Google.Apis.Auth.Tests/OAuth2/Pkcs8Tests.cs, Src/Support/Google.Apis.Auth.Tests/OAuth2/ServiceAccountCredentialTests.cs, Src/Support/Google.Apis.Tests/Google.Apis.Tests.csproj, Src/Support/Google.Apis.Tests/System.Net/AsyncStream.cs, Src/Support/Google.Apis.Tests/System.Net/Extensions.cs, Src/Support/Google.Apis.Tests/System.Net/HttpListener.cs, Src/Support/Google.Apis.Tests/System.Net/HttpListenerContext.cs, Src/Support/Google.Apis.Tests/System.Net/HttpListenerException.cs, Src/Support/Google.Apis.Tests/System.Net/HttpListenerRequest.cs, Src/Support/Google.Apis.Tests/System.Net/HttpListenerResponse.cs, Src/Support/IntegrationTests/IntegrationTests.csproj
As usual, one commit at a time.
=> Several renovate related changes

Src/Support/Google.Apis.Auth.Tests/Google.Apis.Auth.Tests.csproj
=> build: Update Moq dependency.

Src/Support/CommonProjectProperties.xml, features.json
- Repeated enum values for query string parameters are now fully supported.
- Several dependency updates including Newtonsoft.Json to v13
=> Update version: 1.54.0 -> 1.55.0

DiscoveryJson/cloudidentity_v1.json, DiscoveryJson/documentai_v1.json, DiscoveryJson/documentai_v1beta2.json, DiscoveryJson/documentai_v1beta3.json, DiscoveryJson/mybusinesslodging_v1.json, Src/Generated/Google.Apis.CloudIdentity.v1/Google.Apis.CloudIdentity.v1.cs, Src/Generated/Google.Apis.CloudIdentity.v1/Google.Apis.CloudIdentity.v1.csproj, Src/Generated/Google.Apis.Document.v1/Google.Apis.Document.v1.cs, Src/Generated/Google.Apis.Document.v1/Google.Apis.Document.v1.csproj, Src/Generated/Google.Apis.Document.v1beta2/Google.Apis.Document.v1beta2.cs, Src/Generated/Google.Apis.Document.v1beta2/Google.Apis.Document.v1beta2.csproj, Src/Generated/Google.Apis.Document.v1beta3/Google.Apis.Document.v1beta3.cs, Src/Generated/Google.Apis.Document.v1beta3/Google.Apis.Document.v1beta3.csproj, Src/Generated/Google.Apis.MyBusinessLodging.v1/Google.Apis.MyBusinessLodging.v1.cs, Src/Generated/Google.Apis.MyBusinessLodging.v1/Google.Apis.MyBusinessLodging.v1.csproj
=> Release PR: release-2021-09-09.08-00-01

BACKLOG.md
=> chore: Adds #2011 to the backlog.

FAQ.md
=> docs: Add links to OAuth docs in FAQs.

Src/Support/Google.Apis.Auth/SignedTokenVerification.cs, Src/Support/IntegrationTests/SignedTokenVerificationTests.cs
In particular when certificates in a format other than JWK are used.
Closes #2045
=> feat: Improve error messages for JWT validation.

Src/Support/CommonProjectProperties.xml, features.json
Bug fixes:
- #1991. Disables self signed JWTs for domain-wide delegation.
- #2023. Observes execeptions in refresh token tasks.
Features:
- #2037. Adds GoogleCredential.FromJsonParameters.
- #2046. Improves error messages for JWT validation.
Docs:
- #2044. Adds links to OAuth2 docs in FAQs.
=> Update version: 1.55.0 -> 1.56.0

DiscoveryJson/cloudkms_v1.json, DiscoveryJson/dataflow_v1b3.json, DiscoveryJson/logging_v2.json, DiscoveryJson/memcache_v1.json, DiscoveryJson/memcache_v1beta2.json, DiscoveryJson/notebooks_v1.json, DiscoveryJson/run_v2.json, Src/Generated/Google.Apis.AIPlatformNotebooks.v1/Google.Apis.AIPlatformNotebooks.v1.cs, Src/Generated/Google.Apis.AIPlatformNotebooks.v1/Google.Apis.AIPlatformNotebooks.v1.csproj, Src/Generated/Google.Apis.CloudKMS.v1/Google.Apis.CloudKMS.v1.csproj, Src/Generated/Google.Apis.CloudMemorystoreforMemcached.v1/Google.Apis.CloudMemorystoreforMemcached.v1.cs, Src/Generated/Google.Apis.CloudMemorystoreforMemcached.v1/Google.Apis.CloudMemorystoreforMemcached.v1.csproj, Src/Generated/Google.Apis.CloudMemorystoreforMemcached.v1beta2/Google.Apis.CloudMemorystoreforMemcached.v1beta2.cs, Src/Generated/Google.Apis.CloudMemorystoreforMemcached.v1beta2/Google.Apis.CloudMemorystoreforMemcached.v1beta2.csproj, Src/Generated/Google.Apis.CloudRun.v2/Google.Apis.CloudRun.v2.cs, Src/Generated/Google.Apis.CloudRun.v2/Google.Apis.CloudRun.v2.csproj, Src/Generated/Google.Apis.Dataflow.v1b3/Google.Apis.Dataflow.v1b3.cs, Src/Generated/Google.Apis.Dataflow.v1b3/Google.Apis.Dataflow.v1b3.csproj, Src/Generated/Google.Apis.Logging.v2/Google.Apis.Logging.v2.cs, Src/Generated/Google.Apis.Logging.v2/Google.Apis.Logging.v2.csproj
=> Release PR: release-2022-02-21.08-00-02

Src/Support/Google.Apis/Requests/BatchRequest.cs, Src/Support/Google.Apis/Services/BaseClientService.cs
=> feat: Improves deserialization error handling

Src/Support/Google.Apis.Auth.Mvc/Google.Apis.Auth.Mvc.csproj, Src/Support/Google.Apis.Auth.PlatformServices/Google.Apis.Auth.PlatformServices.csproj, Src/Support/Google.Apis.Auth/Google.Apis.Auth.csproj, Src/Support/Google.Apis.Core/Google.Apis.Core.csproj, Src/Support/Google.Apis.PlatformServices/Google.Apis.PlatformServices.csproj, Src/Support/Google.Apis/Google.Apis.csproj
So that the solution builds in Visual Studio 2022
=> build: Include reference assemblies for net45

.github/renovate.json, .github/workflows/build.yml, Src/Support/Google.Apis.Auth.PlatformServices/Google.Apis.Auth.PlatformServices.csproj, Src/Support/Google.Apis.Auth.Tests/Google.Apis.Auth.Tests.csproj, Src/Support/Google.Apis.PlatformServices/Google.Apis.PlatformServices.csproj, Src/Support/Google.Apis.Tests/Google.Apis.Tests.csproj, Src/Support/IntegrationTests/IntegrationTests.csproj
Using reference assemblies if needed.
=> Dependencies updates

.kokoro/BuildGeneratedDocs.sh, .kokoro/BuildSupportDocs.sh
=> docs: Detect docfx failure and abort build

Src/Support/Google.Apis.Auth.Tests/OAuth2/ServiceAccountCredentialTests.cs, Src/Support/Google.Apis.Auth.Tests/OAuth2/TokenFakes.cs
=> tests: Add tests to document SA token fetch retries on exception.

Src/Support/Google.Apis.Auth.Tests/OAuth2/DefaultCredentialProviderTests.cs, Src/Support/Google.Apis.Auth.Tests/OAuth2/ImpersonatedCredentialTests.cs, Src/Support/Google.Apis.Auth.Tests/OAuth2/TokenFakes.cs, Src/Support/Google.Apis.Auth.Tests/OAuth2/UrlSourcedExternalAccountCredentialTest.cs, Src/Support/Google.Apis.Auth/OAuth2/DefaultCredentialProvider.cs, Src/Support/Google.Apis.Auth/OAuth2/ExternalAccountCredential.cs, Src/Support/Google.Apis.Auth/OAuth2/GoogleAuthConsts.cs, Src/Support/Google.Apis.Auth/OAuth2/IGoogleCredential.cs, Src/Support/Google.Apis.Auth/OAuth2/ImpersonatedCredential.cs, Src/Support/Google.Apis.Auth/OAuth2/JsonCredentialParameters.cs, Src/Support/Google.Apis.Auth/OAuth2/Requests/GoogleWifStsTokenRequest.cs, Src/Support/Google.Apis.Auth/OAuth2/Requests/GoogleWifStsTokenRequestExtensions.cs, Src/Support/Google.Apis.Auth/OAuth2/UrlSourcedExternalAccountCredential.cs
Towards #2033
Closes #2146 as this is an alternative implementation.
FYI: @lsirac, @jpassing, @moserware, @TimurSadykov : I'd appreciate your review/comments very much (couldn't add you as reviewers on this repo though).
@jskeet I like this PR better over #2146 because the API surface seems cleaner, but implementation is somewhat more complex, in particular around impersonation.
=> feat: Adds partial support for Workload Identity Federation.

Src/Support/Google.Apis.Auth/OAuth2/ComputeCredential.cs
=> feat: Log errors when pinging metadata server.

Src/Support/Google.Apis.Auth.Tests/OAuth2/AwsExternalAccountCredentialTest.cs, Src/Support/Google.Apis.Auth.Tests/OAuth2/DefaultCredentialProviderTests.cs, Src/Support/Google.Apis.Auth.Tests/OAuth2/ExternalAccountCredentialTestsBase.cs, Src/Support/Google.Apis.Auth.Tests/OAuth2/FileSourcedExternalAccountCredentialTest.cs, Src/Support/Google.Apis.Auth.Tests/OAuth2/TokenFakes.cs, Src/Support/Google.Apis.Auth.Tests/OAuth2/UrlSourcedExternalAccountCredentialTest.cs, Src/Support/Google.Apis.Auth/Google.Apis.Auth.csproj, Src/Support/Google.Apis.Auth/OAuth2/AwsExternalAccountCredential.AwsMetadataServerClient.cs, Src/Support/Google.Apis.Auth/OAuth2/AwsExternalAccountCredential.AwsRegion.cs, Src/Support/Google.Apis.Auth/OAuth2/AwsExternalAccountCredential.AwsSecurityCredential.cs, Src/Support/Google.Apis.Auth/OAuth2/AwsExternalAccountCredential.AwsSignedSubjectToken.cs, Src/Support/Google.Apis.Auth/OAuth2/AwsExternalAccountCredential.UriExtensions.cs, Src/Support/Google.Apis.Auth/OAuth2/AwsExternalAccountCredential.cs, Src/Support/Google.Apis.Auth/OAuth2/DefaultCredentialProvider.cs, Src/Support/Google.Apis.Auth/OAuth2/FileSourcedExternalAccountCredential.cs, Src/Support/Google.Apis.Auth/OAuth2/JsonCredentialParameters.cs, Src/Support/Google.Apis.Auth/OAuth2/UrlSourcedExternalAccountCredential.cs
=> feat: Add support for AWS external account credentials.

BACKLOG.md
=> chore: Update BACKLOG

DiscoveryJson/androidmanagement_v1.json, DiscoveryJson/chat_v1.json, DiscoveryJson/language_v1.json, DiscoveryJson/language_v1beta1.json, DiscoveryJson/language_v1beta2.json, DiscoveryJson/orgpolicy_v2.json, DiscoveryJson/securitycenter_v1.json, DiscoveryJson/securitycenter_v1beta1.json, DiscoveryJson/securitycenter_v1beta2.json, DiscoveryJson/webrisk_v1.json, Src/Generated/Google.Apis.AndroidManagement.v1/Google.Apis.AndroidManagement.v1.cs, Src/Generated/Google.Apis.AndroidManagement.v1/Google.Apis.AndroidManagement.v1.csproj, Src/Generated/Google.Apis.CloudNaturalLanguage.v1/Google.Apis.CloudNaturalLanguage.v1.cs, Src/Generated/Google.Apis.CloudNaturalLanguage.v1/Google.Apis.CloudNaturalLanguage.v1.csproj, Src/Generated/Google.Apis.CloudNaturalLanguage.v1beta1/Google.Apis.CloudNaturalLanguage.v1beta1.cs, Src/Generated/Google.Apis.CloudNaturalLanguage.v1beta1/Google.Apis.CloudNaturalLanguage.v1beta1.csproj, Src/Generated/Google.Apis.CloudNaturalLanguage.v1beta2/Google.Apis.CloudNaturalLanguage.v1beta2.cs, Src/Generated/Google.Apis.CloudNaturalLanguage.v1beta2/Google.Apis.CloudNaturalLanguage.v1beta2.csproj, Src/Generated/Google.Apis.HangoutsChat.v1/Google.Apis.HangoutsChat.v1.cs, Src/Generated/Google.Apis.HangoutsChat.v1/Google.Apis.HangoutsChat.v1.csproj, Src/Generated/Google.Apis.OrgPolicyAPI.v2/Google.Apis.OrgPolicyAPI.v2.cs, Src/Generated/Google.Apis.OrgPolicyAPI.v2/Google.Apis.OrgPolicyAPI.v2.csproj, Src/Generated/Google.Apis.SecurityCommandCenter.v1/Google.Apis.SecurityCommandCenter.v1.cs, Src/Generated/Google.Apis.SecurityCommandCenter.v1/Google.Apis.SecurityCommandCenter.v1.csproj, Src/Generated/Google.Apis.SecurityCommandCenter.v1beta1/Google.Apis.SecurityCommandCenter.v1beta1.cs, Src/Generated/Google.Apis.SecurityCommandCenter.v1beta1/Google.Apis.SecurityCommandCenter.v1beta1.csproj, Src/Generated/Google.Apis.SecurityCommandCenter.v1beta2/Google.Apis.SecurityCommandCenter.v1beta2.cs, Src/Generated/Google.Apis.SecurityCommandCenter.v1beta2/Google.Apis.SecurityCommandCenter.v1beta2.csproj, Src/Generated/Google.Apis.WebRisk.v1/Google.Apis.WebRisk.v1.cs, Src/Generated/Google.Apis.WebRisk.v1/Google.Apis.WebRisk.v1.csproj
=> Release PR: release-2022-10-18.09-22-45

Src/Support/Google.Apis.Tests/Apis/Download/DownloadProgressExtensionsTest.cs, Src/Support/Google.Apis.Tests/Apis/Upload/UploadProgressExtensionsTest.cs, Src/Support/Google.Apis.Tests/Google.Apis.Tests.csproj, Src/Support/Google.Apis/Download/DownloadProgress.cs, Src/Support/Google.Apis/Download/MediaDownloader.cs, Src/Support/Google.Apis/Google.Apis.csproj, Src/Support/Google.Apis/Upload/ResumableUpload.cs, Src/Support/Google.Apis/Upload/UploadProgress.cs
This will help us to diagnose https://github.com/googleapis/google-cloud-dotnet/issues/8552 more easily.
=> feat: Add extension method for progress interfaces to throw exceptions with better stack traces

Src/Support/CommonProjectProperties.xml, features.json
Features:
- #2330 Improves exceptions thrown from progress interfaces.
=> Update version: 1.59.0 => 1.60.0

DiscoveryJson/androidenterprise_v1.json, DiscoveryJson/container_v1.json, DiscoveryJson/content_v2.1.json, DiscoveryJson/healthcare_v1.json, DiscoveryJson/healthcare_v1beta1.json, DiscoveryJson/safebrowsing_v4.json, Src/Generated/Google.Apis.AndroidEnterprise.v1/Google.Apis.AndroidEnterprise.v1.cs, Src/Generated/Google.Apis.AndroidEnterprise.v1/Google.Apis.AndroidEnterprise.v1.csproj, Src/Generated/Google.Apis.CloudHealthcare.v1/Google.Apis.CloudHealthcare.v1.cs, Src/Generated/Google.Apis.CloudHealthcare.v1beta1/Google.Apis.CloudHealthcare.v1beta1.cs, Src/Generated/Google.Apis.Container.v1/Google.Apis.Container.v1.cs, Src/Generated/Google.Apis.Container.v1/Google.Apis.Container.v1.csproj, Src/Generated/Google.Apis.Safebrowsing.v4/Google.Apis.Safebrowsing.v4.cs, Src/Generated/Google.Apis.Safebrowsing.v4/Google.Apis.Safebrowsing.v4.csproj, Src/Generated/Google.Apis.ShoppingContent.v2_1/Google.Apis.ShoppingContent.v2_1.cs, Src/Generated/Google.Apis.ShoppingContent.v2_1/Google.Apis.ShoppingContent.v2_1.csproj
=> Release PR: release-2023-02-20.20-36-27

Src/Support/Google.Apis.Auth.Tests/OAuth2/DefaultCredentialProviderTests.cs, Src/Support/Google.Apis.Auth/OAuth2/DefaultCredentialProvider.cs
=> feat: Improve error when ADC is not configured.

.kokoro/gcp_windows_docker/Dockerfile, RunUnitTests.sh
This PR includes:
- The Windows Dockerfile that will be used for Windows builds.
- A script that runs unit tests.
The rest of the setup is internal.
=> ci: Partial setup for running unit tests in new CI infrastructure.

Src/Support/Google.Apis.Core/Util/Utilities.cs, Src/Support/Google.Apis.Tests/Apis/Utils/UtilitiesTest.cs
=> feat: Utilities in preparation for better date/time parsing

Src/Support/CommonProjectProperties.xml
Features
- #2429 Utilities for date/time parsing.
- #2394 Which improves impersonation support.
- #2349 and #2379 Which improve error reported when ADC is not configured.
=> Update support version: 1.60.0 -> 1.61.0-beta01

Src/Support/CommonProjectProperties.xml
Features
- #2432 More utilities for date/time parsing.
=> Update support version: 1.61.0-beta01 -> 1.61.0-beta02

Src/Support/CommonProjectProperties.xml, features.json
Updates support version: 1.61.0 - beta02 -> 1.61.0
Features
- Improvements for  date/time parsing.
- #2441
- #2432
- #2429
- #2435 PKCE support.
- #2394 Which improves impersonation support.
- #2349 and #2379 Which improve error reported when ADC is not configured.
=> Update version: 1.60.0 -> 1.61.0

.kokoro/autorelease.bat, .kokoro/autorelease.sh
This PR is accompanied by an internal CL.
=> ci: Add Kokoro release scripts.

.kokoro/autorelease.sh
It should be fine to just create and checkout the branch.
=> fix: The git version installed does not support switch.

.kokoro/autorelease.sh
Note: The PR is still being pushed in Draft mode until we confirm pushing to Nuget works well.
=> feat: Make Apiary autorelease actually push to Nuget.

.kokoro/autorelease.sh
It's all working as expected now.
=> feat: Make the new Apiary release PR non-draft.

PostGeneration/dialogflow_v2beta1.sh, Src/Generated/Google.Apis.Dialogflow.v2beta1/Google.Apis.Dialogflow.v2beta1.cs
This is currently blocking all documentation from being generated and pushed. There are bigger aspects to fix here, but this at least gets docs back on track.
=> chore: Fix Dialogflow v2beta1 docs

Src/Generated/Google.Apis.Dialogflow.v2beta1/Google.Apis.Dialogflow.v2beta1.cs
I don't know why this didn't happen last time it was generated.
=> chore: Apply post-processing to Dialogflow v2beta1

BuildGenerated.sh, PostGeneration/admob_v1.sh, PostGeneration/cloudsupport_v2.sh, PostGeneration/cloudsupport_v2beta.sh, PostGeneration/dialogflow_v2beta1.sh
=> fix: Have postgeneration execute again.

BuildGenerated.sh, CSharpGeneratorFunctions.sh, PostGeneration/cloudsupport_v2.sh, PostGeneration/cloudsupport_v2beta.sh, PostGeneration/dialogflow_v2beta1.sh
This PR is currently an update *and* full regeneration. It won't result in anything being uploaded though - so we *might* want to drop the last commit, and just let things regenerate over time.
=> chore: Update generator

.kokoro/BuildSupportDocs.sh
=> chore: Stop generating docs for Google.Apis.Auth.Mvc

Src/Support/CommonProjectProperties.xml, features.json
Features
* #2577 Checks BIOS for detecting GCE residency.
=> Update version: 1.62.1 -> 1.63.0

Src/Support/Google.Apis.Auth.Tests/Google.Apis.Auth.Tests.csproj, Src/Support/Google.Apis.Auth.Tests/OAuth2/FileSourcedExternalAccountCredentialTest.cs, Src/Support/Google.Apis.Auth.Tests/OAuth2/UrlSourcedExternalAccountCredentialTest.cs, Src/Support/Google.Apis.Tests/Apis/Upload/ResumableUploadTest.MultiChunk.cs, Src/Support/Google.Apis.Tests/Apis/Utils/TaskExtensionsTest.cs, Src/Support/Google.Apis.Tests/Google.Apis.Tests.csproj, Src/Support/IntegrationTests/GoogleWebAuthorizationBrokerTests.cs, Src/Support/IntegrationTests/IntegrationTests.csproj
This requires some code changes to avoid ambiguity.
=> chore: Update xUnit to 2.6.0

Src/Support/CommonProjectProperties.xml
Features
* #2595 Which introduces a new class for handling Discovery format.
=> Update support version: 1.63.0 -> 1.64.0-alpha01

CSharpGeneratorFunctions.sh, Src/Support/CommonProjectProperties.xml, features.json
Fixes:
- Discovery date/time types handling: #2575 and #2580
=> Update version: 1.63.0 -> 1.64.0

Src/Support/CommonProjectProperties.xml, features.json
Fixes:
- #2613 Default JSON serializer is not affected by global JSON settings.
- #2630 Tune authorization token staleness and validity windows so that it doesn't overlap with Metadata Server authorization token caching.
Features:
- #2616 Makes batch response handling more efficient, particularly benefiting large responses.
=> Update version: 1.64.0 -> 1.65.0

Src/Support/CommonProjectProperties.xml
- feat: [#2635](https://github.com/googleapis/google-api-dotnet-client/pull/2635) Authentication support for multiple universe domains.
=> Update support version v1.66.0 -> v1.67.0-beta01

Src/Support/Google.Apis.Auth.AspNetCore3.IntegrationTests/Google.Apis.Auth.AspNetCore3.IntegrationTests.csproj, Src/Support/Google.Apis.Auth.Tests/Google.Apis.Auth.Tests.csproj, Src/Support/Google.Apis.Auth/Google.Apis.Auth.csproj, Src/Support/Google.Apis.IntegrationTests/Google.Apis.IntegrationTests.csproj
=> chore: Remove warning suppresions.

Src/Support/CommonProjectProperties.xml
Features
- Universe domain support:
- feat: [#2675](https://github.com/googleapis/google-api-dotnet-client/pull/2675) Universe domain support for Discovery based libraries.
- feat: [#2635](https://github.com/googleapis/google-api-dotnet-client/pull/2635) Universe domain support for authentication.
=> Update support version 1.67.0-beta01 -> 1.67.0

Src/Support/CommonProjectProperties.xml
Features:
- #2703 Support x-goog-api-version header via a new request property
- #2707 Hide Google.Apis.Logging.ILogger from Intellisense
Documentation:
- #2705 Be specific about IDataStore serialization mechanism
=> Update support version 1.67.0 -> 1.68.0

Src/Tools/DiscoveryDocDownloader/Program.cs
- Original code: 201s
- In parallel: 40s
If we skip "poly", which is currently taking a long time to fail with 502 (see internal email):
- Original code: 158s
- In parallel: 5s
So either way, it's a significant difference... and if Poly gets sorted, it'll make the turnaround really quick.
=> tools: Download Discovery docs in parallel

DiscoveryJson/admin_directory_v1.json, DiscoveryJson/admin_directory_v1.json.original, DiscoveryJson/connectors_v1.json, DiscoveryJson/connectors_v2.json, Src/Generated/Google.Apis.Admin.Directory.directory_v1/Google.Apis.Admin.Directory.directory_v1.cs, Src/Generated/Google.Apis.Admin.Directory.directory_v1/Google.Apis.Admin.Directory.directory_v1.csproj, Src/Generated/Google.Apis.Connectors.v1/Google.Apis.Connectors.v1.cs, Src/Generated/Google.Apis.Connectors.v1/Google.Apis.Connectors.v1.csproj, Src/Generated/Google.Apis.Connectors.v2/Google.Apis.Connectors.v2.cs, Src/Generated/Google.Apis.Connectors.v2/Google.Apis.Connectors.v2.csproj
=> Release PR: release-2024-06-17.01-17-49

BuildGenerated.sh, GenerateApis.sh
=> tools: Don't fail if there are no changes to generate/build

.kokoro/autogenerate.sh
=> chore: Update generation title

.kokoro/autogenerate.sh
=> tools: Create a separate commit per API when autogenerating

DiscoveryJson/chat.v1.json, DiscoveryJson/chromepolicy.v1.json, DiscoveryJson/container.v1beta1.json, DiscoveryJson/discoveryengine.v1.json, DiscoveryJson/discoveryengine.v1alpha.json, DiscoveryJson/discoveryengine.v1beta.json, DiscoveryJson/places.v1.json, Src/Generated/Google.Apis.ChromePolicy.v1/Google.Apis.ChromePolicy.v1.cs, Src/Generated/Google.Apis.ChromePolicy.v1/Google.Apis.ChromePolicy.v1.csproj, Src/Generated/Google.Apis.Compute.beta/Google.Apis.Compute.beta.csproj, Src/Generated/Google.Apis.Container.v1beta1/Google.Apis.Container.v1beta1.cs, Src/Generated/Google.Apis.Container.v1beta1/Google.Apis.Container.v1beta1.csproj, Src/Generated/Google.Apis.DiscoveryEngine.v1/Google.Apis.DiscoveryEngine.v1.cs, Src/Generated/Google.Apis.DiscoveryEngine.v1/Google.Apis.DiscoveryEngine.v1.csproj, Src/Generated/Google.Apis.DiscoveryEngine.v1alpha/Google.Apis.DiscoveryEngine.v1alpha.cs, Src/Generated/Google.Apis.DiscoveryEngine.v1alpha/Google.Apis.DiscoveryEngine.v1alpha.csproj, Src/Generated/Google.Apis.DiscoveryEngine.v1beta/Google.Apis.DiscoveryEngine.v1beta.cs, Src/Generated/Google.Apis.DiscoveryEngine.v1beta/Google.Apis.DiscoveryEngine.v1beta.csproj, Src/Generated/Google.Apis.HangoutsChat.v1/Google.Apis.HangoutsChat.v1.cs, Src/Generated/Google.Apis.HangoutsChat.v1/Google.Apis.HangoutsChat.v1.csproj, Src/Generated/Google.Apis.MapsPlaces.v1/Google.Apis.MapsPlaces.v1.cs, Src/Generated/Google.Apis.MapsPlaces.v1/Google.Apis.MapsPlaces.v1.csproj
=> feat: API regeneration: release-2024-08-01.00-20-49

.kokoro/gcp_windows/daily-unit-tests.sh
This will be called from a Kokoro job, CL incoming.
=> ci: Script for daily unit test run

DiscoveryJson/aiplatform.v1.json, DiscoveryJson/aiplatform.v1beta1.json, DiscoveryJson/apikeys.v2.json, DiscoveryJson/chat.v1.json, DiscoveryJson/firebaseml.v2beta.json, DiscoveryJson/manufacturers.v1.json, DiscoveryJson/serviceusage.v1.json, DiscoveryJson/serviceusage.v1beta1.json, DiscoveryJson/storage.v1.json, Src/Generated/Google.Apis.Aiplatform.v1/Google.Apis.Aiplatform.v1.cs, Src/Generated/Google.Apis.Aiplatform.v1/Google.Apis.Aiplatform.v1.csproj, Src/Generated/Google.Apis.Aiplatform.v1beta1/Google.Apis.Aiplatform.v1beta1.csproj, Src/Generated/Google.Apis.ApiKeysService.v2/Google.Apis.ApiKeysService.v2.cs, Src/Generated/Google.Apis.ApiKeysService.v2/Google.Apis.ApiKeysService.v2.csproj, Src/Generated/Google.Apis.Compute.alpha/Google.Apis.Compute.alpha.csproj, Src/Generated/Google.Apis.Compute.beta/Google.Apis.Compute.beta.csproj, Src/Generated/Google.Apis.FirebaseML.v2beta/Google.Apis.FirebaseML.v2beta.csproj, Src/Generated/Google.Apis.HangoutsChat.v1/Google.Apis.HangoutsChat.v1.cs, Src/Generated/Google.Apis.HangoutsChat.v1/Google.Apis.HangoutsChat.v1.csproj, Src/Generated/Google.Apis.ManufacturerCenter.v1/Google.Apis.ManufacturerCenter.v1.cs, Src/Generated/Google.Apis.ManufacturerCenter.v1/Google.Apis.ManufacturerCenter.v1.csproj, Src/Generated/Google.Apis.ServiceUsage.v1/Google.Apis.ServiceUsage.v1.cs, Src/Generated/Google.Apis.ServiceUsage.v1/Google.Apis.ServiceUsage.v1.csproj, Src/Generated/Google.Apis.ServiceUsage.v1beta1/Google.Apis.ServiceUsage.v1beta1.cs, Src/Generated/Google.Apis.ServiceUsage.v1beta1/Google.Apis.ServiceUsage.v1beta1.csproj, Src/Generated/Google.Apis.Storage.v1/Google.Apis.Storage.v1.cs, Src/Generated/Google.Apis.Storage.v1/Google.Apis.Storage.v1.csproj
=> feat: API regeneration: release-2024-08-14.01-03-33

DiscoveryJson/artifactregistry.v1.json, DiscoveryJson/chat.v1.json, DiscoveryJson/cloudasset.v1.json, DiscoveryJson/cloudtrace.v1.json, DiscoveryJson/firebaseml.v2beta.json, DiscoveryJson/monitoring.v3.json, DiscoveryJson/servicenetworking.v1.json, DiscoveryJson/texttospeech.v1.json, DiscoveryJson/texttospeech.v1beta1.json, Src/Generated/Google.Apis.ArtifactRegistry.v1/Google.Apis.ArtifactRegistry.v1.cs, Src/Generated/Google.Apis.ArtifactRegistry.v1/Google.Apis.ArtifactRegistry.v1.csproj, Src/Generated/Google.Apis.CloudAsset.v1/Google.Apis.CloudAsset.v1.cs, Src/Generated/Google.Apis.CloudAsset.v1/Google.Apis.CloudAsset.v1.csproj, Src/Generated/Google.Apis.CloudTrace.v1/Google.Apis.CloudTrace.v1.cs, Src/Generated/Google.Apis.CloudTrace.v1/Google.Apis.CloudTrace.v1.csproj, Src/Generated/Google.Apis.FirebaseML.v2beta/Google.Apis.FirebaseML.v2beta.cs, Src/Generated/Google.Apis.FirebaseML.v2beta/Google.Apis.FirebaseML.v2beta.csproj, Src/Generated/Google.Apis.HangoutsChat.v1/Google.Apis.HangoutsChat.v1.cs, Src/Generated/Google.Apis.HangoutsChat.v1/Google.Apis.HangoutsChat.v1.csproj, Src/Generated/Google.Apis.Monitoring.v3/Google.Apis.Monitoring.v3.csproj, Src/Generated/Google.Apis.ServiceNetworking.v1/Google.Apis.ServiceNetworking.v1.cs, Src/Generated/Google.Apis.ServiceNetworking.v1/Google.Apis.ServiceNetworking.v1.csproj, Src/Generated/Google.Apis.Texttospeech.v1/Google.Apis.Texttospeech.v1.cs, Src/Generated/Google.Apis.Texttospeech.v1/Google.Apis.Texttospeech.v1.csproj, Src/Generated/Google.Apis.Texttospeech.v1beta1/Google.Apis.Texttospeech.v1beta1.cs, Src/Generated/Google.Apis.Texttospeech.v1beta1/Google.Apis.Texttospeech.v1beta1.csproj
=> feat: API regeneration: release-2024-08-21.01-03-31

DiscoveryJson/appengine.v1.json, DiscoveryJson/appengine.v1alpha.json, DiscoveryJson/appengine.v1beta.json, DiscoveryJson/contactcenteraiplatform.v1alpha1.json, DiscoveryJson/file.v1.json, DiscoveryJson/file.v1beta1.json, DiscoveryJson/migrationcenter.v1.json, DiscoveryJson/migrationcenter.v1alpha1.json, Src/Generated/Google.Apis.Appengine.v1/Google.Apis.Appengine.v1.cs, Src/Generated/Google.Apis.Appengine.v1/Google.Apis.Appengine.v1.csproj, Src/Generated/Google.Apis.Appengine.v1alpha/Google.Apis.Appengine.v1alpha.cs, Src/Generated/Google.Apis.Appengine.v1alpha/Google.Apis.Appengine.v1alpha.csproj, Src/Generated/Google.Apis.Appengine.v1beta/Google.Apis.Appengine.v1beta.cs, Src/Generated/Google.Apis.Appengine.v1beta/Google.Apis.Appengine.v1beta.csproj, Src/Generated/Google.Apis.CCAIPlatform.v1alpha1/Google.Apis.CCAIPlatform.v1alpha1.cs, Src/Generated/Google.Apis.CCAIPlatform.v1alpha1/Google.Apis.CCAIPlatform.v1alpha1.csproj, Src/Generated/Google.Apis.CloudFilestore.v1/Google.Apis.CloudFilestore.v1.cs, Src/Generated/Google.Apis.CloudFilestore.v1/Google.Apis.CloudFilestore.v1.csproj, Src/Generated/Google.Apis.CloudFilestore.v1beta1/Google.Apis.CloudFilestore.v1beta1.cs, Src/Generated/Google.Apis.CloudFilestore.v1beta1/Google.Apis.CloudFilestore.v1beta1.csproj, Src/Generated/Google.Apis.MigrationCenterAPI.v1/Google.Apis.MigrationCenterAPI.v1.cs, Src/Generated/Google.Apis.MigrationCenterAPI.v1/Google.Apis.MigrationCenterAPI.v1.csproj, Src/Generated/Google.Apis.MigrationCenterAPI.v1alpha1/Google.Apis.MigrationCenterAPI.v1alpha1.cs, Src/Generated/Google.Apis.MigrationCenterAPI.v1alpha1/Google.Apis.MigrationCenterAPI.v1alpha1.csproj
=> feat: API regeneration: release-2024-09-09.15-35-54

.kokoro/autogenerate.sh
=> tools: Commit enum storage with API changes

.kokoro/daily-unit-tests.sh
I missed this in #2853 
@jskeet Feel free to merge once you've approved.
=> ci: The relative path for the unit tests script has changed.

DiscoveryJson/androidpublisher.v3.json, DiscoveryJson/merchantapi.accounts_v1beta.json, Src/Generated/Google.Apis.AndroidPublisher.v3/Google.Apis.AndroidPublisher.v3.cs, Src/Generated/Google.Apis.AndroidPublisher.v3/Google.Apis.AndroidPublisher.v3.csproj, Src/Generated/Google.Apis.Merchant.accounts_v1beta/Google.Apis.Merchant.accounts_v1beta.cs, Src/Generated/Google.Apis.Merchant.accounts_v1beta/Google.Apis.Merchant.accounts_v1beta.csproj
=> feat: API regeneration: release-2024-10-09.01-03-49

Src/Support/Google.Apis.Auth/OAuth2/GoogleCredential.cs
This applies to Discovery based libraries only. There will be an accompanying PR for GAPICs.
Towards b/371768149
=> chore: Pause automatic requests to MDS Universe Domain endpoint.

DiscoveryJson/connectors.v1.json, DiscoveryJson/content.v2.1.json, DiscoveryJson/dataplex.v1.json, DiscoveryJson/merchantapi.accounts_v1beta.json, DiscoveryJson/merchantapi.products_v1beta.json, DiscoveryJson/networksecurity.v1beta1.json, DiscoveryJson/translate.v3.json, DiscoveryJson/translate.v3beta1.json, Src/Generated/Google.Apis.CloudDataplex.v1/Google.Apis.CloudDataplex.v1.cs, Src/Generated/Google.Apis.CloudDataplex.v1/Google.Apis.CloudDataplex.v1.csproj, Src/Generated/Google.Apis.Connectors.v1/Google.Apis.Connectors.v1.cs, Src/Generated/Google.Apis.Connectors.v1/Google.Apis.Connectors.v1.csproj, Src/Generated/Google.Apis.Merchant.accounts_v1beta/Google.Apis.Merchant.accounts_v1beta.cs, Src/Generated/Google.Apis.Merchant.accounts_v1beta/Google.Apis.Merchant.accounts_v1beta.csproj, Src/Generated/Google.Apis.Merchant.products_v1beta/Google.Apis.Merchant.products_v1beta.cs, Src/Generated/Google.Apis.Merchant.products_v1beta/Google.Apis.Merchant.products_v1beta.csproj, Src/Generated/Google.Apis.NetworkSecurity.v1beta1/Google.Apis.NetworkSecurity.v1beta1.csproj, Src/Generated/Google.Apis.ShoppingContent.v2_1/Google.Apis.ShoppingContent.v2_1.cs, Src/Generated/Google.Apis.ShoppingContent.v2_1/Google.Apis.ShoppingContent.v2_1.csproj, Src/Generated/Google.Apis.Translate.v3/Google.Apis.Translate.v3.cs, Src/Generated/Google.Apis.Translate.v3/Google.Apis.Translate.v3.csproj, Src/Generated/Google.Apis.Translate.v3beta1/Google.Apis.Translate.v3beta1.cs, Src/Generated/Google.Apis.Translate.v3beta1/Google.Apis.Translate.v3beta1.csproj
=> feat: API regeneration: release-2025-04-30.01-03-34

Src/Support/CommonProjectProperties.xml, features.json
Features:
- #2950 Support ExternalAccountAuthorizedUserCredential
- #2921 Support ID token for SAs in other than the default universe domain
=> Update version 1.69.0 -> 1.70.0

ExcludedServices.json
It's failing to generate - see b/447065891 for investigation.
=> chore: exclude aiplatform.v1beta for now

Src/Support/CommonProjectProperties.xml, features.json
Security related fix:
- #3043 Depracate vulnerable credential loading mechanisms. See https://cloud.google.com/docs/authentication/client-libraries#external-credentials for more information.
=> chore: Update version 1.71.0 -> 1.72.0
